import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import JSZip from 'jszip';
import {service} from '../_shared/runtime';import {RendererDiagnosticInput} from '../../packages/contracts';
const dir=path.join(process.env.PRIORITYDESK_DATA_DIR!,'logs');fs.mkdirSync(dir,{recursive:true});
const file=path.join(dir,'structured.jsonl'),rendererFile=path.join(dir,'renderer.jsonl'),recent=new Map<string,number>();
const mask=(value:string)=>value.replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g,'[email masked]').replace(/(password|token|secret)["']?\s*[:=]\s*["']?[^,}\s]+/gi,'$1=[masked]').replace(/[A-Z]:\\[^"\n]+/gi,'[path masked]');
const read=(target=file)=>fs.existsSync(target)?fs.readFileSync(target,'utf8').split('\n').filter(Boolean).map(line=>JSON.parse(line)).reverse():[];
const append=async(target:string,value:unknown)=>{await fs.promises.appendFile(target,JSON.stringify(value)+'\n')};
service('logging-diagnostics',[
  {method:'POST',path:'/v1/write',handler:async({body,requestId})=>{await append(file,{...body,id:body.id||requestId,timestamp:body.timestamp||new Date().toISOString(),details:mask(JSON.stringify(body.details||''))});return{written:true}}},
  {method:'POST',path:'/v1/renderer',handler:async({body,requestId})=>{const event=RendererDiagnosticInput.parse(body),key=[event.type,event.action,event.component,event.errorName].join('|'),time=Date.now();if(time-(recent.get(key)||0)<5000)return{written:false,deduplicated:true};recent.set(key,time);if(recent.size>500)for(const [k,v] of recent)if(time-v>3600000)recent.delete(k);await append(rendererFile,{...event,id:requestId});return{written:true}}},
  {method:'POST',path:'/v1/list',handler:({body})=>read().filter((entry:any)=>(!body?.level||entry.level===body.level)&&(!body?.search||JSON.stringify(entry).toLowerCase().includes(body.search.toLowerCase()))).slice(0,2000)},
  {method:'POST',path:'/v1/clear',handler:async()=>{await Promise.all([fs.promises.writeFile(file,''),fs.promises.writeFile(rendererFile,'')]);return{cleared:true}}},
  {method:'POST',path:'/v1/export',handler:async({body})=>{const rows=read();await fs.promises.writeFile(body.target,body.kind==='logs-json'?JSON.stringify(rows,null,2):rows.map((entry:any)=>`${entry.timestamp} ${entry.level} ${entry.module} ${entry.message}`).join('\n'));return body.target}},
  {method:'POST',path:'/v1/diagnostic',handler:async({body})=>{const zip=new JSZip(),logs=read().filter((entry:any)=>entry.level!=='debug').slice(0,500),renderer=read(rendererFile).slice(0,250);zip.file('system.json',JSON.stringify({appVersion:body.appVersion,platform:process.platform,release:os.release(),arch:os.arch(),services:body.services},null,2));zip.file('logs.json',JSON.stringify(logs,null,2));zip.file('renderer-diagnostics.json',JSON.stringify(renderer,null,2));zip.file('summary.json',JSON.stringify({serviceErrors:logs.filter((x:any)=>x.level==='error').length,serviceWarnings:logs.filter((x:any)=>x.level==='warn').length,rendererErrors:renderer.filter((x:any)=>['error','unhandled_rejection','react_error'].includes(x.type)).length,longTasks:renderer.filter((x:any)=>x.type==='long_task').length,timeouts:renderer.filter((x:any)=>x.type==='api_timeout').length},null,2));zip.file('privacy.txt','Task titles, descriptions, contacts, notes, attachment paths, credentials and secrets are excluded. Renderer diagnostics contain event categories and timings only.');await fs.promises.writeFile(body.path,await zip.generateAsync({type:'nodebuffer'}));return body.path}}
]);
