import {service,call} from '../_shared/runtime';
import {CandidateQuery,ConvertChecklistInput,CreatePrerequisiteInput,DependencyAnalysisQuery,RendererDiagnosticInput,TaskQueryInput} from '../../packages/contracts';
const urls={tasks:process.env.TASKS_URL!,people:process.env.PEOPLE_URL!,data:process.env.DATA_URL!,backup:process.env.BACKUP_URL!,logs:process.env.LOGGING_URL!,reminders:process.env.REMINDERS_URL!,dependencies:process.env.DEPENDENCIES_URL!};
const quiet=new Set(['/v1/reminders/due','/v1/reminders/center']);
const route=(method:string,path:string,target:keyof typeof urls,targetPath:string,validate?:(body:any)=>any)=>({method,path,handler:async({body,requestId}:any)=>{const parsed=validate?validate(body):body;try{const result=await call(urls[target],targetPath,{method:method==='GET'?'GET':'POST',body:parsed,requestId,timeout:path.includes('restore')?60000:12000});if(target!=='logs'&&!quiet.has(path))call(urls.logs,'/v1/write',{method:'POST',body:{level:'info',module:target,message:`${method} ${path}`,requestId},requestId}).catch(()=>{});return result}catch(error){call(urls.logs,'/v1/write',{method:'POST',body:{level:'error',module:target,message:`Request failed: ${method} ${path}`,details:{errorName:(error as Error).name},errorRef:requestId},requestId}).catch(()=>{});throw error}}});
const routes:any[]=[
  route('POST','/v1/tasks/list','tasks','/v1/list',b=>TaskQueryInput.parse(b||{})),route('POST','/v1/tasks/get','tasks','/v1/get'),route('POST','/v1/tasks/save','tasks','/v1/save'),route('POST','/v1/tasks/remove','tasks','/v1/remove'),route('POST','/v1/tasks/restore','tasks','/v1/restore'),route('POST','/v1/tasks/bulk','tasks','/v1/bulk'),route('POST','/v1/tasks/checklist','tasks','/v1/checklist'),
  route('POST','/v1/tasks/candidates','tasks','/v1/candidates',b=>CandidateQuery.parse(b)),route('POST','/v1/tasks/create-prerequisite','tasks','/v1/create-prerequisite',b=>CreatePrerequisiteInput.parse(b)),route('POST','/v1/tasks/convert-checklist','tasks','/v1/convert-checklist',b=>ConvertChecklistInput.parse(b)),
  route('POST','/v1/activities','tasks','/v1/activities'),route('GET','/v1/dashboard','tasks','/v1/dashboard'),route('GET','/v1/workloads','tasks','/v1/workloads'),route('POST','/v1/calendar/range','tasks','/v1/calendar/range'),route('POST','/v1/analytics/dependency-load','dependencies','/v1/people-load',b=>DependencyAnalysisQuery.parse(b||{})),
  route('GET','/v1/people','people','/v1/list'),route('POST','/v1/people/save','people','/v1/save'),route('POST','/v1/people/remove','people','/v1/remove'),
  route('GET','/v1/projects','data','/v1/projects'),route('POST','/v1/projects/save','data','/v1/projects/save'),route('POST','/v1/projects/remove','data','/v1/projects/remove'),route('GET','/v1/settings','data','/v1/settings'),route('POST','/v1/settings','data','/v1/settings'),
  route('POST','/v1/backup/create','backup','/v1/create'),route('POST','/v1/backup/validate','backup','/v1/validate'),route('POST','/v1/backup/restore','backup','/v1/restore'),route('POST','/v1/import/preview','backup','/v1/import/preview'),route('POST','/v1/import/apply','backup','/v1/import/apply'),route('POST','/v1/export','backup','/v1/export'),
  route('POST','/v1/logs','logs','/v1/list'),route('POST','/v1/logs/clear','logs','/v1/clear'),route('POST','/v1/renderer-diagnostics','logs','/v1/renderer',b=>RendererDiagnosticInput.parse(b)),route('POST','/v1/diagnostic','logs','/v1/diagnostic'),route('POST','/v1/logs/export','logs','/v1/export'),
  route('GET','/v1/reminders/due','reminders','/v1/due'),route('GET','/v1/reminders/center','reminders','/v1/center'),route('POST','/v1/reminders/snooze','reminders','/v1/snooze'),route('POST','/v1/reminders/dismiss','reminders','/v1/dismiss')
];
routes.push({method:'GET',path:'/v1/services/health',handler:async({requestId}:any)=>Object.fromEntries(await Promise.all(Object.entries(urls).map(async([name,url])=>{try{return[name,await call(url,'/v1/health',{requestId,timeout:2000})]}catch(error){return[name,{service:name,status:'failed',error:String(error)}]}})))});
service('gateway',routes,urls);
