import type{AuthContext,BaseEnv,Fetcher}from'./types';
export const json=(data:unknown,status=200,requestId:string=crypto.randomUUID(),headers:HeadersInit={})=>new Response(JSON.stringify(status<400?{ok:true,requestId,data}:{ok:false,requestId,error:data}),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
export const failure=(service:string,requestId:string,error:unknown,status=500)=>json({code:error instanceof Error&&error.name==='ZodError'?'INVALID_REQUEST':'SERVICE_ERROR',message:error instanceof Error?error.message:'Unexpected error',service,requestId,retryable:status>=500},status,requestId);
export async function body(request:Request,max=1_000_000){const length=Number(request.headers.get('content-length')||0);if(length>max)throw Object.assign(new Error('Request body is too large'),{status:413});return request.json()}
export function internal(request:Request,env:BaseEnv){if(request.headers.get('x-internal-service-token')!==env.INTERNAL_SERVICE_TOKEN)throw Object.assign(new Error('Internal service authentication failed'),{status:401})}
export function authContext(request:Request):AuthContext{const raw=request.headers.get('x-auth-context');if(!raw)throw Object.assign(new Error('Missing authorization context'),{status:401});return JSON.parse(atob(raw))}
export async function call(binding:Fetcher,path:string,env:BaseEnv,context:AuthContext|undefined,init:RequestInit={}){const headers=new Headers(init.headers);headers.set('x-internal-service-token',env.INTERNAL_SERVICE_TOKEN);if(context)headers.set('x-auth-context',btoa(JSON.stringify(context)));headers.set('content-type','application/json');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10_000);try{const response=await binding.fetch(`https://internal${path}`,{...init,headers,signal:controller.signal});const value=await response.json()as any;if(!response.ok||!value.ok)throw new Error(value.error?.message||`Internal request failed (${response.status})`);return value.data}finally{clearTimeout(timer)}}
export const health=(name:string,dependencies:string[]=[])=>({service:name,status:'ok',version:'v1',dependencies,now:new Date().toISOString()});
export const withRequest=async<E>(service:string,request:Request,env:E,handler:(requestId:string)=>Promise<Response>)=>{const requestId=(request.headers.get('x-request-id')||crypto.randomUUID()).slice(0,100);try{return await handler(requestId)}catch(error){return failure(service,requestId,error,(error as any)?.status||500)}};
