export const STATUSES = ['not_started', 'in_progress', 'waiting', 'blocked', 'completed', 'cancelled', 'archived'] as const;
export const PRIORITIES = ['critical', 'high', 'medium', 'low', 'none'] as const;
export type Status = typeof STATUSES[number];
export type Priority = typeof PRIORITIES[number];
export type ProgressMode = 'automatic' | 'manual' | 'weighted';
export interface ChecklistItem { id:string; taskId:string; description:string; completed:boolean; responsiblePersonId?:string|null; dueDate?:string|null; weight:number; notes:string; position:number; required:boolean; }
export interface Link { id:string; fromTaskId:string; toTaskId:string; type:'blocked_by'|'related'|'parent'; mandatory:boolean; }
export interface Task { id:string; title:string; description:string; status:Status; priority:Priority; startDate?:string|null; dueDate?:string|null; dueTime?:string|null; createdAt:string; updatedAt:string; completedAt?:string|null; projectId?:string|null; categoryId?:string|null; responsiblePersonId?:string|null; tags:string[]; notes:string; progressMode:ProgressMode; manualProgress:number; archived:boolean; deletedAt?:string|null; recurrence?:Recurrence|null; reminder?:Reminder|null; attachments:Attachment[]; checklist:ChecklistItem[]; links:Link[]; blockedReasons?:string[]; calculatedProgress:number; urgencyScore:number; }
export interface Person { id:string; fullName:string; company:string; role:string; phone:string; email:string; address:string; website:string; preferredContact:string; notes:string; tags:string[]; createdAt:string; updatedAt:string; }
export interface Project { id:string; name:string; color:string; description:string; archived:boolean; }
export interface Category { id:string; name:string; color:string; }
export interface Attachment { id:string; name:string; path:string; type:string; }
export interface Recurrence { frequency:'daily'|'weekly'|'monthly'|'yearly'|'weekdays'|'custom'; interval:number; weekdays?:number[]; generation:'schedule'|'completion'; }
export interface Reminder { id:string; at:string; repeatOverdue:boolean; snoozedUntil?:string; fired?:boolean; dismissed?:boolean; }
export interface Activity { id:string; taskId:string; action:string; summary:string; details?:string; createdAt:string; }
export interface LogEntry { id:string; timestamp:string; level:'debug'|'info'|'warn'|'error'; module:string; message:string; details?:string; errorRef?:string; }
export interface Settings { theme:'light'|'dark'|'system'; defaultView:string; defaultSort:string; defaultPriority:Priority; dateFormat:string; firstDay:number; notifications:boolean; quietStart:string; quietEnd:string; startWithWindows:boolean; backupFolder:string; backupFrequency:'off'|'daily'|'weekly'; backupRetention:number; logLevel:string; logRetentionDays:number; trashRetentionDays:number; }
export interface DashboardData { counts:Record<string,number>; needsAttention:Task[]; recent:Task[]; recentlyUnblocked:Task[]; projectProgress:Array<{id:string;name:string;progress:number;active:number}>; workload:Array<{date:string;count:number}>; overallProgress:number; }
export interface TaskQuery { view?:string; search?:string; statuses?:Status[]; priorities?:Priority[]; projectId?:string; responsiblePersonId?:string; due?:'overdue'|'today'|'next7'; dueDate?:string; completedSince?:string; blocked?:boolean; sort?:string; page?:number; pageSize?:number; includeDeleted?:boolean; }
export interface TaskPage { items:Task[]; total:number; page:number; pageSize:number; }
export interface ProjectWorkload { projectId:string; totalTasks:number; completedTasks:number; activeTasks:number; progress:number; }
export interface PersonWorkload { personId:string; totalTasks:number; completedTasks:number; activeTasks:number; progress:number; }
export interface WorkloadSummaries { projects:ProjectWorkload[]; people:PersonWorkload[]; }
export interface BackupPreview { valid:boolean; version?:number; appVersion?:string; createdAt?:string; counts?:Record<string,number>; checksumValid?:boolean; warnings:string[]; errors:string[]; path:string; }
export interface CompletionBlockers { taskId:string; incompleteRequiredChecklist:number; activeMandatoryPrerequisites:number; checklistItemIds:string[]; prerequisites:Array<{id:string;title:string}>; }
export interface PrerequisiteCandidate { id:string; title:string; status:Status; priority:Priority; dueDate?:string|null; projectId?:string|null; responsiblePersonId?:string|null; }
export interface PrerequisiteCandidatePage { items:PrerequisiteCandidate[]; total:number; page:number; pageSize:number; }
export interface TaskRef { id:string; title:string; status:string; priority:string; projectId?:string|null; projectName:string; responsiblePersonId?:string|null; responsiblePersonName:string; dueDate?:string|null; }
export interface DependencyRelationship { prerequisite:TaskRef; affectedTask:TaskRef; depth:number; direct:boolean; path:Array<{id:string;title:string}>; sharedDependency:boolean; otherResponsiblePeople:string[]; daysOverdue:number; }
export interface DependencyLoadPerson { personId:string|null; personName:string; blockingPrerequisites:number; affectedTasks:number; affectedProjects:number; overduePrerequisites:number; criticalHighImpact:number; impactScore:number; scoreBreakdown:Record<string,number>; relationships:DependencyRelationship[]; }
export interface BottleneckAnalysis { generatedAt:string; formula:string; people:DependencyLoadPerson[]; }
export type CalendarReason = 'due'|'reminder'|'completed';
export interface CalendarTask { task:Task; projectName:string; responsiblePersonName:string; reasons:CalendarReason[]; relevantTime?:string|null; blocked:boolean; overdue:boolean; severity:'red'|'orange'|'blue'|'green'; }
export interface CalendarDay { date:string; severity:'red'|'orange'|'blue'|'green'|'neutral'; counts:{total:number;overdue:number;critical:number;high:number;completed:number}; tasks:CalendarTask[]; }
export interface CalendarRange { start:string; end:string; generatedAt:string; days:CalendarDay[]; }
export interface RendererDiagnostic { type:'error'|'unhandled_rejection'|'react_error'|'api_failure'|'api_timeout'|'long_task'|'overlay_anomaly'; durationMs?:number; action?:string; component?:string; errorName?:string; requestId?:string; timestamp:string; }
export interface Api {
  tasks:{list(q?:TaskQuery):Promise<TaskPage>;get(id:string):Promise<Task>;save(task:Partial<Task>&{title:string}):Promise<Task>;remove(id:string,permanent?:boolean):Promise<void>;restore(id:string):Promise<void>;bulk(ids:string[],patch:Partial<Task>):Promise<void>;toggleChecklist(taskId:string,itemId:string,completed:boolean):Promise<Task>;candidates(query:{taskId:string;search?:string;page?:number;pageSize?:number}):Promise<PrerequisiteCandidatePage>;createPrerequisite(input:{waitingTaskId:string;task:Partial<Task>&{title:string};mandatory:boolean}):Promise<{waitingTask:Task;prerequisite:Task}>;convertChecklist(input:{waitingTaskId:string;checklistItemId:string;task:Partial<Task>&{title:string};mandatory:boolean}):Promise<{waitingTask:Task;prerequisite:Task}>};
  people:{list():Promise<Person[]>;save(p:Partial<Person>&{fullName:string}):Promise<Person>;remove(id:string):Promise<void>};projects:{list():Promise<Project[]>;save(p:Partial<Project>&{name:string}):Promise<Project>;remove(id:string):Promise<void>};dashboard():Promise<DashboardData>;workloads():Promise<WorkloadSummaries>;bottlenecks():Promise<BottleneckAnalysis>;calendar:{range(start:string,end:string):Promise<CalendarRange>};reminders:{center():Promise<Array<{task:Task;state:string;actionable:boolean}>>;snooze(taskId:string,until:string):Promise<void>;dismiss(taskId:string):Promise<void>};activities(taskId:string):Promise<Activity[]>;logs(filters?:Record<string,string>):Promise<LogEntry[]>;clearLogs():Promise<void>;rendererDiagnostic(event:RendererDiagnostic):Promise<void>;settings:{get():Promise<Settings>;save(v:Partial<Settings>):Promise<Settings>};backup:{create(description?:string):Promise<string>;validate(path?:string):Promise<BackupPreview>;restore(path:string,mode:'merge'|'replace'):Promise<{message:string;warnings:string[]}>};files:{pick(kind:'file'|'folder'|'backup'|'import'):Promise<string|null>;open(path:string):Promise<void>;addAttachment():Promise<Attachment|null>};export(kind:'csv'|'xlsx'|'json'|'pdf'|'logs-text'|'logs-json'|'diagnostic'):Promise<string>;importData(path:string):Promise<{preview:any;token:string}>;applyImport(token:string,mode:'merge'|'replace'):Promise<{message:string}>;app:{version():Promise<string>;notify(title:string,body:string,taskId?:string):Promise<void>;health():Promise<Record<string,{service:string;status:string;version?:string;uptime?:number;error?:string}>>;supervisorHealth():Promise<any>;restartService(name:string):Promise<void>;restartApplication():Promise<void>};
}
