import {app,BrowserWindow,dialog,ipcMain,Notification,shell} from 'electron';import path from 'node:path';import fs from 'node:fs';import {randomUUID} from 'node:crypto';import {RestartableService} from '../../packages/contracts';import {ServiceSupervisor} from './supervisor';
let win:BrowserWindow|null=null,supervisor:ServiceSupervisor,gateway='';const runtimeRoot=path.join(__dirname,'..');
app.setName('Task Tracker');app.setPath('userData',path.join(app.getPath('appData'),'PriorityDesk'));
function schemaPath(){return path.join(app.getAppPath(),'src','main','schema.sql')}
async function api(pathname:string,body?:unknown,method='POST'){const requestId=randomUUID(),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),pathname.includes('restore')?65000:12000);try{const r=await fetch(`${gateway}${pathname}`,{method,headers:{'content-type':'application/json','x-local-token':supervisor.token,'x-request-id':requestId},body:method==='GET'?undefined:JSON.stringify(body),signal:ctl.signal});const value:any=await r.json();if(!r.ok||!value.ok)throw new Error(`PD_ERROR:${JSON.stringify({...value.error,requestId})}`);return value.data}catch(error){if((error as Error).name==='AbortError')throw new Error(`PD_ERROR:${JSON.stringify({code:'TIMEOUT',message:'The local service did not respond within 12 seconds',service:'gateway',retryable:true,requestId})}`);throw error}finally{clearTimeout(timer)}}
function register(){ipcMain.handle('api',(_e,p,b,m)=>api(p,b,m));ipcMain.handle('native:pick',async(_e,kind)=>{const folder=kind==='folder',backup=kind==='backup';const r=await dialog.showOpenDialog(win!,{properties:[folder?'openDirectory':'openFile'],filters:folder?[]:backup?[{name:'Task Tracker backup',extensions:['zip']}]:[{name:'Supported files',extensions:['csv','xlsx','json','zip']}]});return r.canceled?null:r.filePaths[0]});ipcMain.handle('native:save',async(_e,kind)=>{const ext:Record<string,string>={csv:'csv',xlsx:'xlsx',json:'json',pdf:'pdf',diagnostic:'zip','logs-text':'txt','logs-json':'json'};const r=await dialog.showSaveDialog(win!,{defaultPath:`Task-Tracker-${kind}-${new Date().toISOString().slice(0,10)}.${ext[kind]}`});return r.canceled?null:r.filePath});ipcMain.handle('native:attachment',async()=>{const r=await dialog.showOpenDialog(win!,{properties:['openFile']});if(r.canceled)return null;const p=r.filePaths[0];return{id:randomUUID(),name:path.basename(p),path:p,type:path.extname(p)}});ipcMain.handle('native:open',async(_e,p)=>{if(typeof p!=='string'||!p)throw new Error('Invalid path');if(/^https?:\/\//.test(p))return shell.openExternal(p);const e=await shell.openPath(p);if(e)throw new Error(e)});ipcMain.handle('native:version',()=>app.getVersion());ipcMain.handle('native:notify',(_e,title,body)=>new Notification({title:String(title).slice(0,200),body:String(body).slice(0,500)}).show());ipcMain.handle('native:health',()=>supervisor.health());ipcMain.handle('native:restart-service',(_e,name)=>supervisor.restart(RestartableService.parse(name)));ipcMain.handle('native:restart-app',async()=>{await supervisor.stop();supervisor.shuttingDown=true;app.relaunch();app.exit(0)})}
function createWindow(){win=new BrowserWindow({title:'Task Tracker',icon:path.join(runtimeRoot,'build','brand-icon.ico'),width:1440,height:900,minWidth:900,minHeight:650,show:false,backgroundColor:'#f4f7fb',webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,preload:path.join(__dirname,'preload.cjs')}});win.once('ready-to-show',()=>win?.show());win.webContents.setWindowOpenHandler(({url})=>{if(/^https:\/\//.test(url))shell.openExternal(url);return{action:'deny'}});if(process.env.VITE_DEV_SERVER_URL)win.loadURL(process.env.VITE_DEV_SERVER_URL);else win.loadFile(path.join(runtimeRoot,'dist','index.html'))}
function nativeExtras(){ipcMain.handle('native:set-login',(_e,enabled)=>app.setLoginItemSettings({openAtLogin:Boolean(enabled)}));setInterval(async()=>{try{const due=await api('/v1/reminders/due',undefined,'GET') as Array<{title:string;dueDate?:string}>;for(const t of due)new Notification({title:t.title,body:t.dueDate?`Due ${t.dueDate}`:'Task Tracker reminder'}).show()}catch{}},30000)}
async function boot(){const serviceDir=path.join(runtimeRoot,'dist-services'),dataDir=app.getPath('userData');supervisor=new ServiceSupervisor(serviceDir,dataDir,schemaPath(),app.getVersion(),message=>win?.webContents.send('services:fatal',message));try{gateway=await supervisor.start();register();nativeExtras();createWindow()}catch(e){dialog.showErrorBox('Task Tracker could not start',`${e instanceof Error?e.message:String(e)}\n\nYour data has not been changed. Restart Task Tracker or inspect the local logs.`);await supervisor.stop();app.quit()}}
app.whenReady().then(boot);app.on('before-quit',e=>{if(supervisor&&!supervisor.shuttingDown){e.preventDefault();supervisor.stop().finally(()=>{supervisor.shuttingDown=true;app.quit()})}});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});process.on('uncaughtException',e=>{fs.appendFileSync(path.join(app.getPath('userData'),'supervisor-fallback.log'),`${new Date().toISOString()} ${e.message}\n`)})
