import {contextBridge,ipcRenderer} from 'electron';
import type {Api,RendererDiagnostic} from '../shared/types';
const native=(channel:string,...args:unknown[])=>ipcRenderer.invoke(channel,...args);
const raw=(path:string,body?:unknown,method='POST')=>ipcRenderer.invoke('api',path,body,method);
const request=async(path:string,body?:unknown,method='POST')=>{const started=performance.now();try{return await raw(path,body,method)}catch(error){const message=String(error),event:RendererDiagnostic={type:message.includes('TIMEOUT')?'api_timeout':'api_failure',action:`${method} ${path}`,durationMs:Math.round(performance.now()-started),errorName:(error as Error).name,timestamp:new Date().toISOString()};if(path!=='/v1/renderer-diagnostics')void raw('/v1/renderer-diagnostics',event).catch(()=>{});throw error}finally{const duration=performance.now()-started;if(duration>250&&path!=='/v1/renderer-diagnostics')void raw('/v1/renderer-diagnostics',{type:'long_task',action:`${method} ${path}`,durationMs:Math.round(duration),timestamp:new Date().toISOString()}).catch(()=>{})}};
const api:Api={
  tasks:{list:q=>request('/v1/tasks/list',q),get:id=>request('/v1/tasks/get',{id}),save:task=>request('/v1/tasks/save',task),remove:(id,permanent)=>request('/v1/tasks/remove',{id,permanent}),restore:id=>request('/v1/tasks/restore',{id}),bulk:(ids,patch)=>request('/v1/tasks/bulk',{ids,patch}),toggleChecklist:(taskId,itemId,completed)=>request('/v1/tasks/checklist',{taskId,itemId,completed}),candidates:query=>request('/v1/tasks/candidates',query),createPrerequisite:input=>request('/v1/tasks/create-prerequisite',input),convertChecklist:input=>request('/v1/tasks/convert-checklist',input)},
  people:{list:()=>request('/v1/people',undefined,'GET'),save:person=>request('/v1/people/save',person),remove:id=>request('/v1/people/remove',{id})},
  projects:{list:()=>request('/v1/projects',undefined,'GET'),save:project=>request('/v1/projects/save',project),remove:id=>request('/v1/projects/remove',{id})},
  dashboard:()=>request('/v1/dashboard',undefined,'GET'),workloads:()=>request('/v1/workloads',undefined,'GET'),bottlenecks:()=>request('/v1/analytics/dependency-load',{includePaths:true}),calendar:{range:(start,end)=>request('/v1/calendar/range',{start,end})},
  reminders:{center:()=>request('/v1/reminders/center',undefined,'GET'),snooze:(taskId,until)=>request('/v1/reminders/snooze',{taskId,until}),dismiss:taskId=>request('/v1/reminders/dismiss',{taskId})},
  activities:taskId=>request('/v1/activities',{taskId}),logs:filters=>request('/v1/logs',filters||{}),clearLogs:()=>request('/v1/logs/clear',{}),rendererDiagnostic:event=>request('/v1/renderer-diagnostics',event),
  settings:{get:()=>request('/v1/settings',undefined,'GET'),save:async value=>{const settings=await request('/v1/settings',value);if(value.startWithWindows!==undefined)await native('native:set-login',value.startWithWindows);return settings}},
  backup:{create:description=>request('/v1/backup/create',{description}),validate:async path=>{if(!path)path=await native('native:pick','backup');return path?request('/v1/backup/validate',{path}):{valid:false,warnings:[],errors:['No file selected'],path:''}},restore:(path,mode)=>request('/v1/backup/restore',{path,mode})},
  files:{pick:kind=>native('native:pick',kind),open:path=>native('native:open',path),addAttachment:()=>native('native:attachment')},
  export:async kind=>{const target=await native('native:save',kind);if(!target)return'';if(kind==='diagnostic')return request('/v1/diagnostic',{path:target,appVersion:await native('native:version'),services:await request('/v1/services/health',undefined,'GET')});if(kind==='logs-text'||kind==='logs-json')return request('/v1/logs/export',{kind,target});return request('/v1/export',{kind,target})},
  importData:path=>request('/v1/import/preview',{path}),applyImport:(token,mode)=>request('/v1/import/apply',{token,mode}),
  app:{version:()=>native('native:version'),notify:(title,body,id)=>native('native:notify',title,body,id),health:()=>request('/v1/services/health',undefined,'GET'),supervisorHealth:()=>native('native:health'),restartService:name=>native('native:restart-service',name),restartApplication:()=>native('native:restart-app')}
};
contextBridge.exposeInMainWorld('priorityDesk',api);
