PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,color TEXT NOT NULL DEFAULT '#2563eb',description TEXT NOT NULL DEFAULT '',archived INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS categories(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,color TEXT NOT NULL DEFAULT '#64748b');
CREATE TABLE IF NOT EXISTS people(id TEXT PRIMARY KEY,full_name TEXT NOT NULL,company TEXT NOT NULL DEFAULT '',role TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',website TEXT NOT NULL DEFAULT '',preferred_contact TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',tags TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'not_started',priority TEXT NOT NULL DEFAULT 'medium',start_date TEXT,due_date TEXT,due_time TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,completed_at TEXT,project_id TEXT REFERENCES projects(id),category_id TEXT REFERENCES categories(id),responsible_person_id TEXT REFERENCES people(id),tags TEXT NOT NULL DEFAULT '[]',notes TEXT NOT NULL DEFAULT '',progress_mode TEXT NOT NULL DEFAULT 'automatic',manual_progress INTEGER NOT NULL DEFAULT 0,archived INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,recurrence TEXT,reminder TEXT,attachments TEXT NOT NULL DEFAULT '[]',manual_order INTEGER NOT NULL DEFAULT 0,previous_progress INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS checklist(id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,description TEXT NOT NULL,completed INTEGER NOT NULL DEFAULT 0,responsible_person_id TEXT REFERENCES people(id),due_date TEXT,weight REAL NOT NULL DEFAULT 1,notes TEXT NOT NULL DEFAULT '',position INTEGER NOT NULL DEFAULT 0,required INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS task_links(id TEXT PRIMARY KEY,from_task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,to_task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,type TEXT NOT NULL,mandatory INTEGER NOT NULL DEFAULT 1,CHECK(from_task_id<>to_task_id),UNIQUE(from_task_id,to_task_id,type));
CREATE TABLE IF NOT EXISTS task_contacts(task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,person_id TEXT NOT NULL REFERENCES people(id),role TEXT NOT NULL DEFAULT 'contact',PRIMARY KEY(task_id,person_id,role));
CREATE TABLE IF NOT EXISTS activities(id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,action TEXT NOT NULL,summary TEXT NOT NULL,details TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS app_logs(id TEXT PRIMARY KEY,timestamp TEXT NOT NULL,level TEXT NOT NULL,module TEXT NOT NULL,message TEXT NOT NULL,details TEXT,error_ref TEXT);
CREATE INDEX IF NOT EXISTS idx_tasks_due ON tasks(deleted_at,archived,status,due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id,status);
CREATE INDEX IF NOT EXISTS idx_tasks_updated ON tasks(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_checklist_task ON checklist(task_id,position);
CREATE INDEX IF NOT EXISTS idx_links_from ON task_links(from_task_id);
CREATE INDEX IF NOT EXISTS idx_links_to ON task_links(to_task_id);
CREATE INDEX IF NOT EXISTS idx_checklist_completion ON checklist(task_id,required,completed);
CREATE INDEX IF NOT EXISTS idx_tasks_candidate_search ON tasks(deleted_at,archived,status,title);
CREATE INDEX IF NOT EXISTS idx_logs_time ON app_logs(timestamp DESC);
INSERT OR IGNORE INTO schema_migrations(version,applied_at) VALUES(1,datetime('now'));
INSERT OR IGNORE INTO schema_migrations(version,applied_at) VALUES(2,datetime('now'));
