import { fork, type ChildProcess } from 'node:child_process';
import path from 'node:path';
import { randomBytes, randomUUID } from 'node:crypto';
import type { ServiceName } from '../../packages/contracts';
type Running={name:ServiceName;child:ChildProcess;port:number;url:string;retries:number;critical:boolean;env:Record<string,string>};
export function serviceDirectoryName(name:ServiceName){return name==='gateway'?'api-gateway':name}
export function serviceEntryPath(runtimeDir:string,name:ServiceName){return path.join(runtimeDir,serviceDirectoryName(name),'index.cjs')}
export class ServiceSupervisor{
 token=randomBytes(32).toString('hex');services=new Map<string,Running>();shuttingDown=false;
 constructor(private runtimeDir:string,private dataDir:string,private schema:string,private version:string,private onFatal:(message:string)=>void){}
 private entry(name:ServiceName){return serviceEntryPath(this.runtimeDir,name)}
 private async spawn(name:ServiceName,extra:Record<string,string>={},critical=true,port=0,retries=0):Promise<Running>{return new Promise((resolve,reject)=>{const env={...process.env,ELECTRON_RUN_AS_NODE:'1',PRIORITYDESK_TOKEN:this.token,PRIORITYDESK_DATA_DIR:this.dataDir,PRIORITYDESK_SCHEMA:this.schema,APP_VERSION:this.version,PORT:String(port),...extra} as Record<string,string>;const child=fork(this.entry(name),[],{env,stdio:['ignore','pipe','pipe','ipc']});let settled=false,startupError='';const timer=setTimeout(()=>{if(!settled){settled=true;child.kill();reject(new Error(`${name} timed out during startup${startupError?`: ${startupError}`:''}`))}},12000);child.stdout?.on('data',d=>this.report(name,'info',String(d).trim()));child.stderr?.on('data',d=>{startupError=(startupError+String(d)).trim().slice(-1000);this.report(name,'error',String(d).trim())});child.on('message',(m:any)=>{if(m?.type==='ready'&&!settled){settled=true;clearTimeout(timer);const running={name,child,port:m.port,url:`http://127.0.0.1:${m.port}`,retries,critical,env};this.services.set(name,running);resolve(running)}});child.once('exit',(code,signal)=>{if(!settled){settled=true;clearTimeout(timer);reject(new Error(`${name} exited during startup (${code??signal})${startupError?`: ${startupError}`:''}`))}else this.exited(name,code,signal)});child.once('error',e=>{if(!settled){settled=true;clearTimeout(timer);reject(e)}})})}
 private report(name:string,level:string,message:string){if(!message)return;const logs=this.services.get('logging-diagnostics');if(logs&&name!=='logging-diagnostics')fetch(`${logs.url}/v1/write`,{method:'POST',headers:{'content-type':'application/json','x-local-token':this.token,'x-request-id':randomUUID()},body:JSON.stringify({level,module:`supervisor:${name}`,message})}).catch(()=>{});}
 private exited(name:string,code:number|null,signal:NodeJS.Signals|null){const old=this.services.get(name);this.services.delete(name);if(this.shuttingDown||!old)return;if(old.retries>=2){if(old.critical)this.onFatal(`${name} could not be recovered after ${old.retries} restart attempts.`);return}const extra=Object.fromEntries(Object.entries(old.env).filter(([k])=>['DATA_URL','TASKS_URL','DEPENDENCIES_URL','REMINDERS_URL','PEOPLE_URL','BACKUP_URL','LOGGING_URL'].includes(k)));setTimeout(()=>this.spawn(old.name,extra,old.critical,old.port,old.retries+1).catch(e=>{if(old.critical)this.onFatal(String(e))}),500*(old.retries+1));this.report(name,'error',`Exited (${code??signal}); restart ${old.retries+1}/2 scheduled`)}
 async start(){const logs=await this.spawn('logging-diagnostics',{},false);const data=await this.spawn('data');const deps=await this.spawn('dependencies-progress',{DATA_URL:data.url});const reminders=await this.spawn('reminders',{DATA_URL:data.url},false);const people=await this.spawn('people',{DATA_URL:data.url});const tasks=await this.spawn('tasks',{DATA_URL:data.url,DEPENDENCIES_URL:deps.url,REMINDERS_URL:reminders.url});const backup=await this.spawn('backup-migration',{DATA_URL:data.url,TASKS_URL:tasks.url});const gateway=await this.spawn('gateway',{DATA_URL:data.url,TASKS_URL:tasks.url,DEPENDENCIES_URL:deps.url,REMINDERS_URL:reminders.url,PEOPLE_URL:people.url,BACKUP_URL:backup.url,LOGGING_URL:logs.url});return gateway.url}
 async restart(name:ServiceName){const old=this.services.get(name);if(!old)throw new Error(`${name} is not running`);if(name==='data')throw new Error('Restart the application to restart the Data service safely');this.services.delete(name);old.child.send?.({type:'shutdown'});await new Promise<void>(resolve=>{const timer=setTimeout(resolve,2500);old.child.once('exit',()=>{clearTimeout(timer);resolve()})});const extra=Object.fromEntries(Object.entries(old.env).filter(([key])=>['DATA_URL','TASKS_URL','DEPENDENCIES_URL','REMINDERS_URL','PEOPLE_URL','BACKUP_URL','LOGGING_URL'].includes(key)));await this.spawn(name,extra,old.critical,old.port,0)}
 health(){return [...this.services.values()].map(s=>({name:s.name,port:s.port,retries:s.retries,running:!s.child.killed}))}
 async stop(){this.shuttingDown=true;await Promise.all([...this.services.values()].map(s=>new Promise<void>(resolve=>{const timer=setTimeout(()=>{s.child.kill();resolve()},2500);s.child.once('exit',()=>{clearTimeout(timer);resolve()});s.child.send?.({type:'shutdown'})})));this.services.clear()}
}
