import {randomUUID} from 'node:crypto';
import {service,call} from '../_shared/runtime';
import {CalendarRangeQuery,CandidateQuery,ConvertChecklistInput,CreatePrerequisiteInput,TaskInput,TaskQueryInput} from '../../packages/contracts';
import {buildCalendarRange} from '../../src/shared/analytics';
import type {DashboardData,Person,PrerequisiteCandidatePage,Project,Task,TaskPage,WorkloadSummaries} from '../../src/shared/types';
const data=process.env.DATA_URL!,dependencies=process.env.DEPENDENCIES_URL!,reminders=process.env.REMINDERS_URL!;
const enrich=(items:Task[],requestId:string)=>call<Task[]>(dependencies,'/v1/enrich',{method:'POST',body:{tasks:items},requestId});
function nextDate(value:string|undefined|null,recurrence:NonNullable<Task['recurrence']>){const d=value?new Date(`${value}T12:00:00`):new Date(),n=Math.max(1,recurrence.interval||1);if(recurrence.frequency==='daily'||recurrence.frequency==='custom')d.setDate(d.getDate()+n);else if(recurrence.frequency==='weekly')d.setDate(d.getDate()+7*n);else if(recurrence.frequency==='monthly')d.setMonth(d.getMonth()+n);else if(recurrence.frequency==='yearly')d.setFullYear(d.getFullYear()+n);else{do d.setDate(d.getDate()+1);while(d.getDay()===0||d.getDay()===6)}return d.toISOString().slice(0,10)}
async function save(body:any,requestId:string){
  const value=TaskInput.parse(body);if(value.startDate&&value.dueDate&&value.dueDate<value.startDate)throw new Error('Due date cannot precede start date');
  let previous:Task|undefined;if(body.id)try{previous=await call<Task>(data,'/v1/tasks/get',{method:'POST',body:{id:body.id},requestId})}catch{}
  if(body.links?.length){const page=await call<TaskPage>(data,'/v1/tasks/list',{method:'POST',body:{pageSize:10000},requestId}),existing=page.items.flatMap(t=>t.links);await call(dependencies,'/v1/validate-links',{method:'POST',body:{taskId:body.id||'new',proposed:body.links,existing},requestId})}
  const task=await call<Task>(data,'/v1/tasks/save',{method:'POST',body,requestId});
  call(reminders,'/v1/sync',{method:'POST',body:{task},requestId}).catch(()=>{});
  if(task.status==='completed'&&previous?.status!=='completed'&&task.recurrence){const nextChecklist=task.checklist.map((c,i)=>({...c,id:randomUUID(),taskId:'',completed:false,position:i}));const next=await call<Task>(data,'/v1/tasks/save',{method:'POST',body:{...task,id:undefined,status:'not_started',completedAt:null,dueDate:nextDate(task.dueDate,task.recurrence),startDate:task.startDate?nextDate(task.startDate,task.recurrence):null,checklist:nextChecklist,reminder:task.reminder?{...task.reminder,id:randomUUID(),at:nextDate(task.dueDate,task.recurrence)+'T09:00',fired:false}:null},requestId});call(reminders,'/v1/sync',{method:'POST',body:{task:next},requestId}).catch(()=>{})}
  return(await enrich([task],requestId))[0];
}
service('tasks',[
  {method:'POST',path:'/v1/list',handler:async({body,requestId})=>{const query=TaskQueryInput.parse(body||{}),page=await call<TaskPage>(data,'/v1/tasks/list',{method:'POST',body:query,requestId});page.items=await enrich(page.items,requestId);page.items.sort((a,b)=>query.sort==='title'?a.title.localeCompare(b.title):b.urgencyScore-a.urgencyScore);return page}},
  {method:'POST',path:'/v1/get',handler:async({body,requestId})=>(await enrich([await call<Task>(data,'/v1/tasks/get',{method:'POST',body,requestId})],requestId))[0]},
  {method:'POST',path:'/v1/save',handler:({body,requestId})=>save(body,requestId)},
  {method:'POST',path:'/v1/remove',handler:({body,requestId})=>call(data,'/v1/tasks/remove',{method:'POST',body,requestId})},
  {method:'POST',path:'/v1/restore',handler:({body,requestId})=>call(data,'/v1/tasks/restore',{method:'POST',body,requestId})},
  {method:'POST',path:'/v1/bulk',handler:({body,requestId})=>call(data,'/v1/tasks/bulk',{method:'POST',body,requestId})},
  {method:'POST',path:'/v1/checklist',handler:async({body,requestId})=>(await enrich([await call<Task>(data,'/v1/tasks/checklist',{method:'POST',body,requestId})],requestId))[0]},
  {method:'POST',path:'/v1/candidates',handler:({body,requestId})=>call<PrerequisiteCandidatePage>(data,'/v1/tasks/candidates',{method:'POST',body:CandidateQuery.parse(body),requestId})},
  {method:'POST',path:'/v1/create-prerequisite',handler:async({body,requestId})=>{const input=CreatePrerequisiteInput.parse(body);const result=await call<{waitingTask:Task;prerequisite:Task}>(data,'/v1/tasks/create-prerequisite',{method:'POST',body:input,requestId});call(reminders,'/v1/sync',{method:'POST',body:{task:result.prerequisite},requestId}).catch(()=>{});return{waitingTask:(await enrich([result.waitingTask],requestId))[0],prerequisite:(await enrich([result.prerequisite],requestId))[0]}}},
  {method:'POST',path:'/v1/convert-checklist',handler:async({body,requestId})=>{const input=ConvertChecklistInput.parse(body);const result=await call<{waitingTask:Task;prerequisite:Task}>(data,'/v1/tasks/convert-checklist',{method:'POST',body:input,requestId});call(reminders,'/v1/sync',{method:'POST',body:{task:result.prerequisite},requestId}).catch(()=>{});return{waitingTask:(await enrich([result.waitingTask],requestId))[0],prerequisite:(await enrich([result.prerequisite],requestId))[0]}}},
  {method:'POST',path:'/v1/activities',handler:({body,requestId})=>call(data,'/v1/activities',{method:'POST',body,requestId})},
  {method:'GET',path:'/v1/dashboard',handler:async({requestId})=>{const page=await call<TaskPage>(data,'/v1/tasks/list',{method:'POST',body:{pageSize:10000},requestId}),all=await enrich(page.items,requestId),today=new Date().toISOString().slice(0,10),week=new Date(Date.now()+7*864e5).toISOString().slice(0,10),projects=await call<Project[]>(data,'/v1/projects',{requestId}),done=await call<TaskPage>(data,'/v1/tasks/list',{method:'POST',body:{view:'completed',pageSize:10000},requestId});const counts={overdue:all.filter(t=>t.dueDate&&t.dueDate<today).length,today:all.filter(t=>t.dueDate===today).length,next7:all.filter(t=>t.dueDate&&t.dueDate>today&&t.dueDate<=week).length,critical:all.filter(t=>t.priority==='critical').length,high:all.filter(t=>t.priority==='high').length,blocked:all.filter(t=>t.blockedReasons?.length).length,waiting:all.filter(t=>t.status==='waiting').length,recentCompleted:done.items.filter(t=>Date.now()-new Date(t.completedAt||0).getTime()<7*864e5).length,active:all.length};return{counts,needsAttention:[...all].sort((a,b)=>b.urgencyScore-a.urgencyScore).slice(0,12),recent:[...all].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,6),recentlyUnblocked:[],projectProgress:projects.map(p=>{const a=all.filter(t=>t.projectId===p.id);return{id:p.id,name:p.name,active:a.length,progress:a.length?Math.round(a.reduce((s,t)=>s+t.calculatedProgress,0)/a.length):0}}),workload:Array.from({length:7},(_,i)=>{const date=new Date(Date.now()+i*864e5).toISOString().slice(0,10);return{date,count:all.filter(t=>t.dueDate===date).length}}),overallProgress:all.length?Math.round(all.reduce((s,t)=>s+t.calculatedProgress,0)/all.length):0} as DashboardData}},
  {method:'GET',path:'/v1/workloads',handler:async({requestId})=>{const activePage=await call<TaskPage>(data,'/v1/tasks/list',{method:'POST',body:{pageSize:10000},requestId}),completedPage=await call<TaskPage>(data,'/v1/tasks/list',{method:'POST',body:{view:'completed',pageSize:10000},requestId}),active=await enrich(activePage.items,requestId),completed=await enrich(completedPage.items,requestId),all=[...active,...completed];const summarize=(id:string,key:'projectId'|'responsiblePersonId')=>{const tasks=all.filter(task=>task[key]===id),done=tasks.filter(task=>task.status==='completed').length;return{totalTasks:tasks.length,completedTasks:done,activeTasks:tasks.length-done,progress:tasks.length?Math.round(tasks.reduce((sum,task)=>sum+task.calculatedProgress,0)/tasks.length):0}};const projects=await call<Project[]>(data,'/v1/projects',{requestId}),people=await call<Person[]>(data,'/v1/people',{requestId});return{projects:projects.map(project=>({projectId:project.id,...summarize(project.id,'projectId')})),people:people.map(person=>({personId:person.id,...summarize(person.id,'responsiblePersonId')}))} as WorkloadSummaries}},
  {method:'POST',path:'/v1/calendar/range',handler:async({body,requestId})=>{const query=CalendarRangeQuery.parse(body),snapshot=await call<{tasks:Task[];people:Person[];projects:Project[]}>(data,'/v1/read-model/calendar',{method:'POST',body:query,requestId});snapshot.tasks=await enrich(snapshot.tasks,requestId);return buildCalendarRange(snapshot.tasks,snapshot.projects,snapshot.people,query.start,query.end)}}
],{data,dependencies,reminders});
