name = "task-tracker-identity-access"
main = "../dist-connected-workers/identity-access/index.mjs"
compatibility_date = "2026-09-01"
workers_dev = false
[[services]]
binding = "DATA"
service = "task-tracker-data"
[vars]
ENVIRONMENT = "production"
APP_URL = "https://task-tracker-63a.pages.dev"
CONNECTED_USER_LIMIT = "20"
