name = "task-tracker-notifications"
main = "../dist-connected-workers/notifications/index.mjs"
compatibility_date = "2026-09-01"
workers_dev = false
[[services]]
binding = "DATA"
service = "task-tracker-data"
[vars]
ENVIRONMENT = "production"
EMAIL_DAILY_CEILING = "75"
APP_URL = "https://task-tracker-63a.pages.dev"
