const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL as string,ANON_KEY=import.meta.env.VITE_SUPABASE_ANON_KEY as string,APP_URL=(import.meta.env.VITE_APP_URL||location.origin)as string,KEY='tt-connected-session';
export type Session={access_token:string;refresh_token:string;expires_at:number;user:{id:string;email?:string}};export type AuthLinkMode='invite'|'recovery'|null;
export const session={get:():Session|null=>{if(import.meta.env.VITE_DEMO_MODE==='true')return{access_token:'demo',refresh_token:'demo',expires_at:4102444800,user:{id:'demo',email:'demo@example.test'}};try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}},set:(value:Session|null)=>value?localStorage.setItem(KEY,JSON.stringify(value)):localStorage.removeItem(KEY)};
async function auth(path:string,payload:unknown,method='POST',token?:string){const response=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method,headers:{apikey:ANON_KEY,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:payload===undefined?undefined:JSON.stringify(payload)}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.msg||data.error_description||data.message||'Authentication failed');return data}
function save(data:any){const value={...data,expires_at:data.expires_at||Math.floor(Date.now()/1000)+Number(data.expires_in||3600)};session.set(value);return value}
export async function signIn(email:string,password:string){return save(await auth('token?grant_type=password',{email,password}))}
export async function requestPasswordReset(email:string){await auth('recover',{email,redirect_to:`${APP_URL}/?auth=recovery`});return{sent:true}}
export const resetPassword=requestPasswordReset;
export async function updatePassword(password:string){const token=await accessToken();if(!token)throw new Error('Authentication required');return auth('user',{password},'PUT',token)}
export async function signOut(scope:'local'|'global'='local'){const current=session.get();if(current)await auth(`logout?scope=${scope}`,{},'POST',current.access_token).catch(()=>undefined);session.set(null)}
export async function refresh(){const current=session.get();if(!current)throw new Error('No session');return save(await auth('token?grant_type=refresh_token',{refresh_token:current.refresh_token}))}
export async function accessToken(){let current=session.get();if(current&&current.expires_at-Date.now()/1000<60)current=await refresh();return current?.access_token}
export async function consumeAuthLink():Promise<AuthLinkMode>{const url=new URL(location.href),hash=new URLSearchParams(url.hash.replace(/^#/,'')),mode=(url.searchParams.get('auth')||hash.get('type'))as AuthLinkMode;const access=hash.get('access_token'),refreshToken=hash.get('refresh_token');if(access&&refreshToken)save({access_token:access,refresh_token:refreshToken,expires_in:Number(hash.get('expires_in')||3600),user:{id:'pending'}});else if(url.searchParams.get('code')){const verifier=sessionStorage.getItem('tt-pkce-verifier');if(verifier)save(await auth('token?grant_type=pkce',{auth_code:url.searchParams.get('code'),code_verifier:verifier}))}url.hash='';['code','token_hash','type','auth'].forEach(k=>url.searchParams.delete(k));history.replaceState(null,'',url.pathname+url.search);return mode==='invite'||mode==='recovery'?mode:null}
