const today=new Date().toISOString().slice(0,10),inDays=(n:number)=>new Date(Date.now()+n*864e5).toISOString().slice(0,10);const tasks=[{id:'11111111-1111-4111-8111-111111111111',title:'Prepare customer presentation',description:'Finalize the slides and send the review copy.',status:'in_progress',priority:'critical',dueDate:today,dueTime:'16:00',projectId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',projectName:'Customer Delivery',responsiblePersonName:'Davide',calculatedProgress:65,blocked:false,version:2,updatedAt:new Date().toISOString()},{id:'22222222-2222-4222-8222-222222222222',title:'Order replacement component',description:'Waiting for supplier confirmation.',status:'waiting',priority:'high',dueDate:inDays(3),projectId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',projectName:'Home',responsiblePersonName:'Mattia',calculatedProgress:25,blocked:true,version:1,updatedAt:new Date().toISOString()},{id:'33333333-3333-4333-8333-333333333333',title:'Submit permit documents',description:'Upload approved drawings.',status:'not_started',priority:'medium',dueDate:inDays(7),projectName:'Terrace',responsiblePersonName:'Saurabh',calculatedProgress:10,blocked:false,version:1,updatedAt:new Date().toISOString()}];
export function demo(path:string){
  if(path.startsWith('/tasks/details'))return{task:tasks[0],checklist:[{id:'44444444-4444-4444-8444-444444444444',taskId:tasks[0].id,description:'Confirm agenda',completed:true,required:true,position:0,costAmount:null},{id:'55555555-5555-4555-8555-555555555555',taskId:tasks[0].id,description:'Finish product slides',completed:false,required:true,position:1,costAmount:45}],dependencies:[]};
  if(path.startsWith('/tasks/attachments'))return[];
  if(path.startsWith('/tasks'))return{items:tasks,total:tasks.length};
  if(path==='/dashboard')return{counts:{overdue:1,today:1,next7:2,critical:1,blocked:1,waiting:1,active:3},overallProgress:43,projectProgress:[],peopleProgress:[],workload:[]};
  if(path==='/projects')return[{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',name:'Customer Delivery',color:'#1d4ed8',description:'Client work',progress:65,activeTasks:1,version:1},{id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',name:'Terrace',color:'#f97316',description:'Terrace workstream',progress:38,activeTasks:4,version:1}];
  if(path==='/people/linked-projects')return[{id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',shareId:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',projectId:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',name:'Airbnb Como',color:'#16a34a',description:'Shared business project',progress:68,activeTasks:5,version:1,allowChecklistUpdates:true,allowTaskCompletion:true,allowComments:true,token:'demo',verificationToken:'demo'}];
  if(path.startsWith('/people'))return[{id:'11111111-1111-4111-8111-111111111111',fullName:'Davide Giusti',role:'Project manager',company:'',progress:58,activeTasks:8},{id:'22222222-2222-4222-8222-222222222222',fullName:'Mattia Manfreda',role:'Contractor',company:'Build Co.',progress:42,activeTasks:6},{id:'33333333-3333-4333-8333-333333333333',fullName:'Saurabh Patel',role:'Advisor',company:'',progress:76,activeTasks:2}];
  if(path.startsWith('/calendar'))return Array.from({length:31},(_,i)=>{const date=`${today.slice(0,8)}${String(i+1).padStart(2,'0')}`,items=tasks.filter(t=>t.dueDate===date);return{date,severity:items.some(t=>t.priority==='critical')?'red':items.some(t=>t.priority==='high')?'orange':items.length?'blue':'neutral',count:items.length,tasks:items}});
  if(path==='/access/state')return{platformAdmin:true};
  if(path==='/access/users')return[{id:'66666666-6666-4666-8666-666666666666',email:'colleague@example.com',status:'accepted',invitedAt:new Date().toISOString(),expiresAt:inDays(7),acceptedUserId:'77777777-7777-4777-8777-777777777777'},{id:'88888888-8888-4888-8888-888888888888',email:'pending@example.com',status:'pending',invitedAt:new Date().toISOString(),expiresAt:inDays(7)}];
  if(path==='/access/usage')return{acceptedUsers:2,pendingInvitations:1,userLimit:20,pendingDeliveries:0,failedNotifications:0,emailsSentToday:3};
  if(path==='/dependencies/people-load')return[{personId:'22222222-2222-4222-8222-222222222222',personName:'Mattia Manfreda',blockingPrerequisites:2,affectedTasks:5,affectedProjects:2,overduePrerequisites:1,criticalHighImpact:2,impactScore:155},{personId:null,personName:'Unassigned',blockingPrerequisites:1,affectedTasks:2,affectedProjects:1,overduePrerequisites:0,criticalHighImpact:0,impactScore:40}];
  if(path==='/preferences')return{emailEnabled:true,pushEnabled:true,reminder:true,dueToday:true,overdue:true,dailySummary:false,timezone:'Europe/Rome',quietStart:'22:00',quietEnd:'07:00',currencyCode:'CHF'};
  if(path==='/notifications/readiness')return{email:{providerConfigured:true,accountAddressAvailable:true,enabled:true},push:{providerConfigured:true,enabled:true,activeSubscriptions:1},scheduler:{cadenceMinutes:5,explicitTaskReminders:true,dueTodayAutomation:false,overdueAutomation:false,dailySummaryAutomation:false},deliveries:{pending:0,failed:0,delivered:8,latest:{status:'delivered',createdAt:new Date().toISOString(),deliveredAt:new Date().toISOString(),errorCode:null}}};
  if(path.startsWith('/diagnostics'))return{services:[{name:'Gateway',status:'healthy',latencyMs:42,version:'1.4.0'},{name:'Tasks',status:'healthy',latencyMs:38,version:'1.4.0'},{name:'Notifications',status:'healthy',latencyMs:51,version:'1.4.0'}],events:[{id:'99999999-9999-4999-8999-999999999999',createdAt:new Date().toISOString(),level:'info',service:'connected-gateway',eventType:'health.check',requestId:'demo-request',summary:'All connected services are available',details:{demo:true}}],privacy:'Secrets and personal data are redacted.',environment:'demo',generatedAt:new Date().toISOString(),requestId:'demo-request',level:'info'};
  return null;
}
