import { useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, CssBaseline, Divider, LinearProgress, List, ListItem, ListItemText, Stack, Step, StepLabel, Stepper, ThemeProvider, Typography, createTheme } from '@mui/material';
import { AddToHomeScreen, CheckCircle, NotificationsActive, TaskAlt } from '@mui/icons-material';
import { api, publicApi } from './api';
import { PWA_INSTALL_RETURN_PATH_KEY, PwaInstallInstructions, usePwaInstall } from './PwaInstallPrompt';

type Invitation = { shareId: string; token: string; inviterName: string; personName: string; projectId: string; projectName: string; projectDescription?: string; expiresAt?: string | null; offerNotifications: boolean; activeTasks: number; openChecklistItems: number; permissions: { readOnly: boolean; allowChecklistUpdates: boolean; allowTaskCompletion: boolean; allowComments: boolean; allowCreateEditTasks: boolean; allowManageChecklistItems: boolean } };
const PENDING_JOIN_PATH = 'task-tracker:pending-invitation-path';

export function ProjectInvitationOnboarding({ signedIn }: { signedIn: boolean }) {
  const install = usePwaInstall(), code = decodeURIComponent(location.pathname.split('/join/')[1] || '');
  const [invitation, setInvitation] = useState<Invitation | null>(null), [step, setStep] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const theme = useMemo(() => createTheme({ palette: { mode: matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light', primary: { main: '#2563eb' } }, shape: { borderRadius: 14 }, typography: { fontFamily: 'Inter,Segoe UI,Arial,sans-serif', h4: { fontWeight: 800 } } }), []);
  useEffect(() => { publicApi<Invitation>(`/public/project-invitation?code=${encodeURIComponent(code)}`).then(setInvitation).catch(reason => setError((reason as Error).message)); }, [code]);
  const accept = async () => { setBusy(true); setError(''); try { await api('/people/accept-project-invitation', { method: 'POST', body: { code } }); setStep(3); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const signIn = () => { localStorage.setItem(PENDING_JOIN_PATH, location.pathname); location.href = '/'; };
  const continueGuest = () => { if (invitation) location.href = `/shared-tasks?token=${encodeURIComponent(invitation.token)}`; };
  const requestInstall = () => { localStorage.setItem(PWA_INSTALL_RETURN_PATH_KEY, location.pathname); void install.requestInstall(); };
  const permissions = invitation ? ['View the shared project', invitation.permissions.allowChecklistUpdates && 'Complete assigned checklist items', invitation.permissions.allowTaskCompletion && 'Complete assigned tasks', invitation.permissions.allowComments && 'Comment on shared work', invitation.permissions.allowCreateEditTasks && 'Create and edit project tasks', invitation.permissions.allowManageChecklistItems && 'Manage checklist items'].filter(Boolean) as string[] : [];
  return <ThemeProvider theme={theme}><CssBaseline/><Box sx={{ minHeight: '100dvh', bgcolor: 'background.default', p: { xs: 2, sm: 4 } }}><Card sx={{ maxWidth: 720, mx: 'auto' }}><CardContent sx={{ p: { xs: 2.5, sm: 4 } }}>
    <Stack direction="row" spacing={1} alignItems="center" mb={3}><TaskAlt color="primary"/><Typography fontWeight={850}>Task Tracker</Typography></Stack>
    <Stepper activeStep={step} alternativeLabel sx={{ mb: 4 }}><Step><StepLabel>Welcome</StepLabel></Step><Step><StepLabel>Access</StepLabel></Step><Step><StepLabel>Accept</StepLabel></Step><Step><StepLabel>Ready</StepLabel></Step></Stepper>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{!invitation && !error && <LinearProgress/>}
    {invitation && step === 0 && <Stack spacing={2}><Typography variant="h4">Welcome to Task Tracker</Typography><Typography variant="h6">{invitation.inviterName} invited you to collaborate on:</Typography><Card variant="outlined"><CardContent><Typography variant="h5" fontWeight={800}>{invitation.projectName}</Typography>{invitation.projectDescription && <Typography color="text.secondary" mt={.5}>{invitation.projectDescription}</Typography>}<Stack direction="row" gap={1} mt={2} flexWrap="wrap"><Chip label={`${invitation.activeTasks} active tasks`}/><Chip label={`${invitation.openChecklistItems} open checklist items`}/></Stack></CardContent></Card><Alert severity="info">You will only see information explicitly shared with you.</Alert><Button variant="contained" onClick={() => setStep(1)}>Continue</Button></Stack>}
    {invitation && step === 1 && <Stack spacing={2}><Typography variant="h4">Your access</Typography><List>{permissions.map(label => <ListItem key={label} disableGutters><CheckCircle color="success" sx={{ mr: 1.5 }}/><ListItemText primary={label}/></ListItem>)}</List><Divider/><Typography fontWeight={800}>You cannot</Typography><Typography color="text.secondary">See {invitation.inviterName}’s private workspace, view unrelated projects, or change project access.</Typography><Button variant="contained" onClick={() => setStep(2)}>Continue</Button></Stack>}
    {invitation && step === 2 && <Stack spacing={2}><Typography variant="h4">Choose how to continue</Typography>{signedIn ? <><Alert severity="info">The live project will be added under <strong>Shared with me</strong>. It will not be copied into your private workspace.</Alert><Button variant="contained" disabled={busy} onClick={() => void accept()}>{busy ? <CircularProgress size={20}/> : 'Accept project'}</Button><Button color="inherit" onClick={() => history.back()}>Decline</Button></> : <><Button variant="contained" onClick={continueGuest}>Continue as guest</Button><Typography variant="body2" color="text.secondary">No account required. Updates require email verification.</Typography><Button variant="outlined" onClick={signIn}>Sign in to Task Tracker</Button><Typography variant="caption" color="text.secondary">New Task Tracker accounts remain invite-only. Existing users should sign in with the email address that received this invitation.</Typography></>}</Stack>}
    {invitation && step === 3 && <Stack spacing={2}><Typography variant="h4">You’re ready</Typography><Alert severity="success">{invitation.projectName} has been added to Shared with me.</Alert>{invitation.offerNotifications && <Card variant="outlined"><CardContent><Stack direction="row" spacing={1} alignItems="center"><NotificationsActive color="primary"/><Typography fontWeight={800}>Stay updated</Typography></Stack><Typography color="text.secondary" my={1.5}>Would you like notifications for deadlines and project changes? Browser permission is requested only after you choose to enable notifications.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Button variant="outlined" onClick={() => { location.href = '/?view=settings&setup=notifications'; }}>Enable notifications</Button><Button color="inherit" onClick={() => { location.href = '/?view=projects'; }}>Not now</Button></Stack></CardContent></Card>}{!install.installed && <Card variant="outlined"><CardContent><Stack direction="row" spacing={1} alignItems="center"><AddToHomeScreen color="primary"/><Typography fontWeight={800}>Install Task Tracker</Typography></Stack><Typography color="text.secondary" my={1.5}>Install the app for faster access and reliable notifications.</Typography><Button variant="outlined" onClick={requestInstall}>Install Task Tracker</Button></CardContent></Card>}<Button variant="contained" onClick={() => { location.href = '/?view=projects'; }}>Open shared projects</Button><PwaInstallInstructions/></Stack>}
  </CardContent></Card></Box></ThemeProvider>;
}

export function consumePendingInvitationPath() { const value = localStorage.getItem(PENDING_JOIN_PATH); if (value) localStorage.removeItem(PENDING_JOIN_PATH); return value; }
