import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardActionArea, CardContent, Checkbox, Chip, Collapse, CssBaseline, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControlLabel, IconButton, LinearProgress, Paper, Stack, Switch, TextField, ThemeProvider, ToggleButton, ToggleButtonGroup, Typography, createTheme } from '@mui/material';
import { DarkMode, ExpandLess, ExpandMore, LightMode, Lock, NotificationsActive, Refresh, TaskAlt, VerifiedUser } from '@mui/icons-material';
import { publicApi } from './api';

type SharedChecklist = { id: string; description: string; completed: boolean; required: boolean; position: number; version: number };
type SharedTask = { id: string; title: string; description?: string; status: string; priority: string; dueDate?: string | null; calculatedProgress: number; blocked: boolean; checklist: SharedChecklist[]; version: number; responsiblePersonId?: string | null; responsiblePersonName?: string | null; canUpdateChecklist: boolean; canComplete: boolean; canComment: boolean };
type SharedProject = { projectId?: string | null; projectName: string; progress: number; tasks: SharedTask[] };
type SharedProjectPerson = { personId: string; fullName: string; company?: string; role?: string; phone?: string | null; email?: string | null; address?: string | null; notes?: string | null; sharePhone: boolean; shareEmail: boolean; shareAddress: boolean; shareNotes: boolean; supervisable: boolean };
type SharedPreferences = { emailAvailable: boolean; emailEnabled: boolean; pushEnabled: boolean; activePushSubscriptions: number };
type SharedAccess = { scopeMode: 'assigned' | 'project'; projectId?: string | null; expiresAt?: string | null; allowChecklistUpdates: boolean; allowTaskCompletion: boolean; allowComments: boolean; allowViewProjectContacts: boolean; allowViewContactAssignments: boolean; allowSuperviseContactChecklists: boolean; allowCompleteContactTasks: boolean; allowManageProjectContacts: boolean };
type SharedView = { personName: string; generatedAt: string; preferences: SharedPreferences; access: SharedAccess; projects: SharedProject[]; projectPeople: SharedProjectPerson[] };
type ItemFilter = 'todo' | 'done' | 'all';
const emptyContactForm = { fullName: '', role: '', company: '', phone: '', email: '', address: '', notes: '', sharePhone: false, shareEmail: false, shareAddress: false, shareNotes: false, supervisable: false };
const label = (value: string) => value.replaceAll('_', ' ').replace(/^./, character => character.toUpperCase());
const applicationServerKey = (value: string) => { const padding = '='.repeat((4 - value.length % 4) % 4), raw = atob((value + padding).replace(/-/g, '+').replace(/_/g, '/')); return Uint8Array.from(raw, character => character.charCodeAt(0)); };

export function PublicPersonTasks() {
  const token = new URLSearchParams(location.search).get('token') || '', verificationKey = `share-verification:${token.slice(0, 36)}`;
  const [data, setData] = useState<SharedView | null>(null), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const [expanded, setExpanded] = useState<string | null>(null), [filter, setFilter] = useState<ItemFilter>('todo'), [code, setCode] = useState(''), [destination, setDestination] = useState('');
  const [manageOpen, setManageOpen] = useState(false), [editingContact, setEditingContact] = useState<string | null>(null), [contactForm, setContactForm] = useState(emptyContactForm);
  const [verified, setVerified] = useState(() => Boolean(sessionStorage.getItem(verificationKey))), [comments, setComments] = useState<Record<string, string>>({});
  const [dark, setDark] = useState(() => localStorage.getItem('shared-task-theme') === 'dark' || (!localStorage.getItem('shared-task-theme') && matchMedia('(prefers-color-scheme: dark)').matches));
  const theme = useMemo(() => createTheme({ palette: { mode: dark ? 'dark' : 'light', primary: { main: dark ? '#60a5fa' : '#1d4ed8' }, background: { default: dark ? '#0c1220' : '#f4f7fb', paper: dark ? '#151d2e' : '#fff' } }, shape: { borderRadius: 14 }, typography: { fontFamily: 'Inter,Segoe UI,Arial,sans-serif', h4: { fontWeight: 800 }, h6: { fontWeight: 750 } } }), [dark]);
  const load = useCallback(async () => { setError(''); try { setData(await publicApi<SharedView>(`/public/person-tasks?token=${encodeURIComponent(token)}`)); } catch (reason) { setError((reason as Error).message); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  const setTheme = (next: boolean) => { setDark(next); localStorage.setItem('shared-task-theme', next ? 'dark' : 'light'); };
  const write = async (path: string, input: object, success: string) => { setBusy(true); setError(''); setMessage(''); try { await publicApi(path, { method: 'POST', body: { token, ...input }, headers: { 'X-Share-Verification': sessionStorage.getItem(verificationKey) || '' } }); await load(); setMessage(success); return true; } catch (reason) { const text = (reason as Error).message; setError(text); if (/verification|expired|invalid/i.test(text)) { sessionStorage.removeItem(verificationKey); setVerified(false); } return false; } finally { setBusy(false); } };
  const requestCode = async () => { setBusy(true); setError(''); try { const result = await publicApi<{ destination: string }>('/public/person-verification/request', { method: 'POST', body: { token } }); setDestination(result.destination); setMessage(`Verification code sent to ${result.destination}.`); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const verifyCode = async () => { setBusy(true); setError(''); try { const result = await publicApi<{ verificationToken: string }>('/public/person-verification/verify', { method: 'POST', body: { token, code } }); sessionStorage.setItem(verificationKey, result.verificationToken); setVerified(true); setCode(''); setMessage('Email verified. You can update assigned work for 30 minutes.'); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const savePreferences = async (changes: Partial<Pick<SharedPreferences, 'emailEnabled' | 'pushEnabled'>>) => { setBusy(true); setError(''); try { await publicApi('/public/person-preferences', { method: 'POST', body: { token, ...changes } }); await load(); setMessage('Notification preferences updated.'); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const enablePush = async () => { setBusy(true); setError(''); try { if (!('serviceWorker' in navigator) || !('PushManager' in window)) throw new Error('Browser notifications are not supported on this device.'); if (!import.meta.env.VITE_VAPID_PUBLIC_KEY) throw new Error('Browser notification configuration is unavailable.'); const permission = await Notification.requestPermission(); if (permission !== 'granted') throw new Error('Notification permission was not granted.'); const registration = await navigator.serviceWorker.ready, subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: applicationServerKey(import.meta.env.VITE_VAPID_PUBLIC_KEY) as BufferSource }), json = subscription.toJSON(); await publicApi('/public/person-push-subscribe', { method: 'POST', body: { token, ...json, expirationTime: json.expirationTime ?? null, deviceLabel: navigator.userAgent.slice(0, 100) } }); await load(); setMessage('Browser notifications enabled.'); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const taskCount = data?.projects.reduce((sum, project) => sum + project.tasks.length, 0) || 0, writable = Boolean(data?.access && (data.access.allowChecklistUpdates || data.access.allowTaskCompletion || data.access.allowComments || data.access.allowSuperviseContactChecklists || data.access.allowCompleteContactTasks || data.access.allowManageProjectContacts));
  return <ThemeProvider theme={theme}><CssBaseline/><Box sx={{ minHeight: '100vh', bgcolor: 'background.default', py: { xs: 2, sm: 5 }, px: 2 }}><Box sx={{ maxWidth: 780, mx: 'auto' }}>
    <Stack direction="row" alignItems="center" spacing={1.25} mb={3}><TaskAlt color="primary"/><Box flex={1}><Typography variant="h4">Shared work</Typography><Typography color="text.secondary">{data?.personName || 'Collaboration portal'}</Typography></Box><IconButton aria-label="Use light mode" color={!dark ? 'primary' : 'default'} onClick={() => setTheme(false)}><LightMode/></IconButton><IconButton aria-label="Use dark mode" color={dark ? 'primary' : 'default'} onClick={() => setTheme(true)}><DarkMode/></IconButton></Stack>
    <Alert severity="info" sx={{ mb: 2 }} action={<Button startIcon={<Refresh/>} onClick={() => void load()}>Refresh</Button>}>This is a live, read-only view until permitted updates are email-verified. Updates need an internet connection and are never queued offline.</Alert>
    {message && <Alert severity="success" onClose={() => setMessage('')} sx={{ mb: 2 }}>{message}</Alert>}{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{!data && !error && <LinearProgress/>}
    {data && <Stack spacing={2}>
      {writable && <Card variant="outlined"><CardContent><Stack direction="row" spacing={1} alignItems="center"><VerifiedUser color={verified ? 'success' : 'action'}/><Typography variant="h6">Secure updates</Typography></Stack>{verified ? <Alert severity="success" sx={{ mt: 1.5 }}>Email verified. You may update your own assignments and only explicitly supervisable contact work.</Alert> : <><Typography color="text.secondary" my={1.5}>Verify the email recorded by the workspace owner before changing work.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Button variant="outlined" startIcon={<Lock/>} disabled={busy} onClick={() => void requestCode()}>Send verification code</Button><TextField size="small" label="6-digit code" value={code} onChange={event => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} helperText={destination ? `Sent to ${destination}` : ''}/><Button variant="contained" disabled={busy || code.length !== 6} onClick={() => void verifyCode()}>Verify</Button></Stack></>}</CardContent></Card>}
      <Card variant="outlined"><CardContent><Stack direction="row" alignItems="center" spacing={1} mb={1}><NotificationsActive color="primary"/><Typography variant="h6">Updates</Typography></Stack><Typography color="text.secondary" mb={1.5}>Choose how to receive changes to shared work.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><FormControlLabel control={<Switch disabled={busy || !data.preferences.emailAvailable} checked={data.preferences.emailEnabled} onChange={event => void savePreferences({ emailEnabled: event.target.checked })}/>} label={data.preferences.emailAvailable ? 'Email updates' : 'Email unavailable'}/><FormControlLabel control={<Switch disabled={busy} checked={data.preferences.pushEnabled && data.preferences.activePushSubscriptions > 0} onChange={event => event.target.checked ? void enablePush() : void savePreferences({ pushEnabled: false })}/>} label="Browser notifications"/></Stack></CardContent></Card>
      {data.access.scopeMode === 'project' && <Button variant="outlined" onClick={() => { location.href = `/?claimProject=${encodeURIComponent(token)}`; }}>Add to my Task Tracker</Button>}
      {(data.projectPeople?.length > 0 || data.access.allowManageProjectContacts) && <Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center" mb={1.5}><Typography variant="h6">Project people</Typography>{data.access.allowManageProjectContacts && <Button size="small" disabled={!verified} onClick={() => { setEditingContact(null); setContactForm(emptyContactForm); setManageOpen(true); }}>Add contact</Button>}</Stack><Stack spacing={1.25}>{data.projectPeople.map(person => <Paper key={person.personId} variant="outlined" sx={{ p: 1.5 }}><Typography fontWeight={750}>{person.fullName}</Typography><Typography variant="body2" color="text.secondary">{[person.role, person.company].filter(Boolean).join(' · ') || 'Project contact'}</Typography><Stack direction="row" flexWrap="wrap" useFlexGap gap={1} mt={1}>{person.phone && <Button size="small" href={`tel:${person.phone}`}>{person.phone}</Button>}{person.email && <Button size="small" href={`mailto:${person.email}`}>{person.email}</Button>}{person.address && <Button size="small" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(person.address)}`} target="_blank" rel="noreferrer">Directions</Button>}</Stack>{person.notes && <Typography variant="body2" sx={{ mt: 1, whiteSpace: 'pre-wrap' }}>{person.notes}</Typography>}{person.supervisable && <Chip size="small" color="secondary" label="Supervisable contact" sx={{ mt: 1 }}/>} {data.access.allowManageProjectContacts && <Stack direction="row" spacing={1} mt={1}><Button size="small" disabled={!verified} onClick={() => { setEditingContact(person.personId); setContactForm({ fullName: person.fullName, role: person.role || '', company: person.company || '', phone: person.phone || '', email: person.email || '', address: person.address || '', notes: person.notes || '', sharePhone: person.sharePhone, shareEmail: person.shareEmail, shareAddress: person.shareAddress, shareNotes: person.shareNotes, supervisable: person.supervisable }); setManageOpen(true); }}>Edit</Button><Button size="small" color="error" disabled={!verified || busy} onClick={() => void write('/public/person-project-person', { action: 'remove', personId: person.personId }, `${person.fullName} removed from this project.`)}>Remove</Button></Stack>}</Paper>)}</Stack></CardContent></Card>}
      <Typography color="text.secondary">{taskCount} active task{taskCount === 1 ? '' : 's'} across {data.projects.length} project{data.projects.length === 1 ? '' : 's'} · refreshed {new Date(data.generatedAt).toLocaleString()}</Typography>
      {!data.projects.length ? <Alert severity="success">No active tasks are currently shared.</Alert> : data.projects.map(project => { const key = project.projectId || 'none', open = expanded === key, checklist = project.tasks.flatMap(task => task.checklist), done = checklist.filter(item => item.completed).length; return <Card key={key} variant="outlined"><CardActionArea onClick={() => setExpanded(open ? null : key)}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center" gap={2}><Box flex={1}><Typography variant="h6">{project.projectName}</Typography><Typography color="text.secondary">{project.tasks.length} task{project.tasks.length === 1 ? '' : 's'} · {done}/{checklist.length} checklist items done</Typography></Box>{open ? <ExpandLess/> : <ExpandMore/>}</Stack><Stack direction="row" justifyContent="space-between" mt={2}><Typography variant="body2">Project progress</Typography><Typography variant="body2" fontWeight={700}>{project.progress || 0}%</Typography></Stack><LinearProgress variant="determinate" value={project.progress || 0} sx={{ mt: 1, height: 8, borderRadius: 4 }}/></CardContent></CardActionArea>
        <Collapse in={open} unmountOnExit><Divider/><Box sx={{ p: 2 }}><ToggleButtonGroup exclusive size="small" value={filter} onChange={(_, value) => value && setFilter(value)} sx={{ mb: 2 }}><ToggleButton value="todo">To do</ToggleButton><ToggleButton value="done">Done</ToggleButton><ToggleButton value="all">All</ToggleButton></ToggleButtonGroup><Stack spacing={1.5}>{project.tasks.map(task => { const items = task.checklist.filter(item => filter === 'all' || (filter === 'done' ? item.completed : !item.completed)); if (!items.length && task.checklist.length && filter !== 'all') return null; const onBehalf = Boolean(task.responsiblePersonName && task.responsiblePersonName !== data.personName && (task.canUpdateChecklist || task.canComplete)); return <Paper key={task.id} variant="outlined" sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography fontWeight={750}>{task.title}</Typography>{task.description && <Typography variant="body2" color="text.secondary" sx={{ whiteSpace: 'pre-wrap' }}>{task.description}</Typography>}</Box><Stack direction="row" spacing={0.5} flexWrap="wrap" useFlexGap>{task.blocked && <Chip size="small" color="warning" label="Blocked"/>}<Chip size="small" variant="outlined" label={label(task.priority)}/></Stack></Stack><Typography variant="caption" color="text.secondary">{label(task.status)} · {task.dueDate ? `Due ${new Date(`${task.dueDate}T12:00:00`).toLocaleDateString()}` : 'No due date'}{task.responsiblePersonName ? ` · Assigned to ${task.responsiblePersonName}` : ''}</Typography>{onBehalf && <Alert severity="info" sx={{ mt: 1 }}>Your updates will be recorded as made by {data.personName} on behalf of {task.responsiblePersonName}.</Alert>}
          {task.checklist.length ? <Stack mt={1.5}>{items.map(item => <Stack key={item.id} direction="row" alignItems="center"><Checkbox checked={item.completed} disabled={busy || !verified || !task.canUpdateChecklist} size="small" onChange={event => void write('/public/person-checklist', { itemId: item.id, completed: event.target.checked, expectedVersion: item.version }, onBehalf ? `Checklist updated on behalf of ${task.responsiblePersonName}.` : 'Checklist updated.')}/><Typography sx={{ textDecoration: item.completed ? 'line-through' : 'none', color: item.completed ? 'text.secondary' : 'text.primary' }}>{item.description}</Typography>{item.required && <Chip label="Required" size="small" sx={{ ml: 'auto' }}/>}</Stack>)}</Stack> : <Alert severity="info" sx={{ mt: 1.5 }}>This task has no checklist items.</Alert>}
          {(task.canComplete || task.canComment) && <Stack spacing={1} mt={2}>{task.canComplete && task.status !== 'completed' && <Button variant="contained" disabled={busy || !verified} onClick={() => void write('/public/person-complete', { taskId: task.id, expectedVersion: task.version }, onBehalf ? `Task completed on behalf of ${task.responsiblePersonName}.` : 'Task marked complete.')}>Mark task complete</Button>}{task.canComment && <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField fullWidth size="small" label="Add a comment" value={comments[task.id] || ''} onChange={event => setComments(value => ({ ...value, [task.id]: event.target.value }))}/><Button variant="outlined" disabled={busy || !verified || !(comments[task.id] || '').trim()} onClick={async () => { if (await write('/public/person-comment', { taskId: task.id, comment: comments[task.id] }, 'Comment sent to the workspace owner.')) setComments(value => ({ ...value, [task.id]: '' })); }}>Send</Button></Stack>}</Stack>}
          {!task.canUpdateChecklist && !task.canComplete && !task.canComment && writable && <Alert severity="info" sx={{ mt: 1.5 }}>You can view this task, but you do not have permission to update it.</Alert>}
        </Paper>; })}</Stack></Box></Collapse></Card>; })}
    </Stack>}
    <Dialog open={manageOpen} onClose={() => !busy && setManageOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editingContact ? 'Edit project contact' : 'Add project contact'}</DialogTitle><DialogContent><Stack spacing={1.5} mt={1}><Alert severity="warning">Changes update the owner's live People record. Use this only for contacts the owner has authorised you to manage.</Alert><TextField label="Full name" value={contactForm.fullName} onChange={e => setContactForm(v => ({ ...v, fullName: e.target.value }))}/><TextField label="Function / role" value={contactForm.role} onChange={e => setContactForm(v => ({ ...v, role: e.target.value }))}/><TextField label="Company" value={contactForm.company} onChange={e => setContactForm(v => ({ ...v, company: e.target.value }))}/><TextField label="Phone" value={contactForm.phone} onChange={e => setContactForm(v => ({ ...v, phone: e.target.value }))}/><TextField label="Email" type="email" value={contactForm.email} onChange={e => setContactForm(v => ({ ...v, email: e.target.value.toLowerCase() }))}/><TextField label="Address" value={contactForm.address} onChange={e => setContactForm(v => ({ ...v, address: e.target.value }))}/><TextField multiline minRows={2} label="Notes" value={contactForm.notes} onChange={e => setContactForm(v => ({ ...v, notes: e.target.value }))}/><FormControlLabel control={<Switch checked={contactForm.sharePhone} onChange={e => setContactForm(v => ({ ...v, sharePhone: e.target.checked }))}/>} label="Share phone"/><FormControlLabel control={<Switch checked={contactForm.shareEmail} onChange={e => setContactForm(v => ({ ...v, shareEmail: e.target.checked }))}/>} label="Share email"/><FormControlLabel control={<Switch checked={contactForm.shareAddress} onChange={e => setContactForm(v => ({ ...v, shareAddress: e.target.checked }))}/>} label="Share address"/><FormControlLabel control={<Switch checked={contactForm.shareNotes} onChange={e => setContactForm(v => ({ ...v, shareNotes: e.target.checked }))}/>} label="Share notes"/><FormControlLabel control={<Switch checked={contactForm.supervisable} onChange={e => setContactForm(v => ({ ...v, supervisable: e.target.checked }))}/>} label="Supervisable"/></Stack></DialogContent><DialogActions><Button disabled={busy} onClick={() => setManageOpen(false)}>Cancel</Button><Button variant="contained" disabled={busy || !verified || !contactForm.fullName.trim()} onClick={async () => { const ok = await write('/public/person-project-person', { action: editingContact ? 'update' : 'create', ...(editingContact ? { personId: editingContact } : {}), ...contactForm, email: contactForm.email.trim().toLowerCase() }, editingContact ? 'Project contact updated.' : 'Project contact added.'); if (ok) setManageOpen(false); }}>{editingContact ? 'Save changes' : 'Add contact'}</Button></DialogActions></Dialog>
    <Typography variant="caption" color="text.secondary" display="block" textAlign="center" mt={4}>Verified collaboration portal · Access can be expired or revoked by the workspace owner</Typography>
  </Box></Box></ThemeProvider>;
}
