import { useMemo, useState } from 'react';
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Chip, InputAdornment, Stack, TextField, Typography } from '@mui/material';
import { ExpandMore, Search } from '@mui/icons-material';
import { CONNECTED_RELEASE } from '../../../packages/connected-contracts/release';

type ManualSection = { title: string; keywords: string; content: React.ReactNode };
type ManualPoint = { label: string; x: number; y: number; direction: 'up' | 'right' | 'down' | 'left' };
type ManualVisualData = { src: string; mobile?: boolean; points: ManualPoint[] };

const manualVisuals: ManualVisualData[] = [
  { src: '/manual/navigation.png', mobile: true, points: [{ label: 'Theme and account controls', x: 82, y: 4, direction: 'left' }, { label: 'Primary mobile navigation', x: 36, y: 96, direction: 'up' }, { label: 'More menu', x: 88, y: 96, direction: 'up' }] },
  { src: '/manual/tasks.png', points: [{ label: 'Task filters and search', x: 38, y: 24, direction: 'up' }, { label: 'Table, cards and refresh controls', x: 56, y: 34, direction: 'up' }, { label: 'Task cards open their details', x: 49, y: 49, direction: 'down' }] },
  { src: '/manual/task-editor.png', points: [{ label: 'Task identity and description', x: 28, y: 19, direction: 'right' }, { label: 'Status, owner, project and dates', x: 47, y: 46, direction: 'right' }, { label: 'Save task', x: 88, y: 95, direction: 'left' }] },
  { src: '/manual/checklist.png', points: [{ label: 'Checklist section', x: 18, y: 83, direction: 'up' }, { label: 'New checklist item', x: 42, y: 89, direction: 'right' }, { label: 'Add checklist item', x: 82, y: 89, direction: 'left' }] },
  { src: '/manual/dependencies.png', points: [{ label: 'Dependency impact totals', x: 35, y: 36, direction: 'up' }, { label: 'Person-level bottleneck', x: 49, y: 58, direction: 'right' }, { label: 'Open affected work', x: 82, y: 68, direction: 'left' }] },
  { src: '/manual/projects.png', points: [{ label: 'Create a project', x: 88, y: 14, direction: 'left' }, { label: 'Project card and progress', x: 29, y: 31, direction: 'down' }, { label: 'Project actions', x: 28, y: 47, direction: 'up' }] },
  { src: '/manual/people.png', points: [{ label: 'Create a person', x: 88, y: 14, direction: 'left' }, { label: 'Responsibility and progress', x: 29, y: 35, direction: 'down' }, { label: 'Recap and contact actions', x: 29, y: 48, direction: 'up' }] },
  { src: '/manual/projects.png', points: [{ label: 'Linked projects are separate', x: 20, y: 61, direction: 'up' }, { label: 'Open the shared project', x: 40, y: 76, direction: 'right' }, { label: 'Linked access indicator', x: 84, y: 69, direction: 'left' }] },
  { src: '/manual/settings.png', points: [{ label: 'Live notification controls', x: 26, y: 27, direction: 'right' }, { label: 'Reminder email controls', x: 28, y: 49, direction: 'right' }, { label: 'Notification readiness', x: 31, y: 72, direction: 'right' }] },
  { src: '/manual/access.png', points: [{ label: 'User and delivery summary', x: 29, y: 31, direction: 'right' }, { label: 'Invite a user', x: 50, y: 43, direction: 'up' }, { label: 'Expandable access groups', x: 33, y: 65, direction: 'right' }] },
  { src: '/manual/diagnostics.png', points: [{ label: 'Refresh or download diagnostics', x: 84, y: 17, direction: 'left' }, { label: 'Connected service health', x: 48, y: 43, direction: 'down' }, { label: 'Recent service events', x: 50, y: 76, direction: 'up' }] }
];

const arrowRotation = { right: '0deg', down: '90deg', left: '180deg', up: '-90deg' } as const;

function ManualVisual({ index }: { index: number }) {
  const visual = manualVisuals[index];
  return <Box mt={2}><Typography fontWeight={700} mb={1}>Visual guide</Typography><Box sx={{ position: 'relative', width: visual.mobile ? 'min(100%, 390px)' : 'min(100%, 683px)', aspectRatio: visual.mobile ? '390 / 844' : '1180 / 760', mx: 'auto', borderRadius: 2, overflow: 'hidden', border: 1, borderColor: 'divider', bgcolor: 'background.default' }}><Box component="img" src={visual.src} alt={`Annotated Task Tracker view for ${visual.points.map(point => point.label).join(', ')}`} sx={{ position: 'absolute', inset: 0, display: 'block', width: '100%', height: '100%' }}/>{visual.points.map((point, pointIndex) => <Box key={point.label} aria-hidden sx={{ position: 'absolute', top: `${point.y}%`, left: `${point.x}%`, transform: 'translate(-50%,-50%)', width: 30, height: 30, borderRadius: '50%', display: 'grid', placeItems: 'center', bgcolor: 'primary.main', color: 'primary.contrastText', fontWeight: 800, boxShadow: 3, border: '2px solid white', '&:after': { content: '"➜"', position: 'absolute', left: 25, top: -4, color: 'primary.main', fontSize: 30, lineHeight: 1, transform: `rotate(${arrowRotation[point.direction]})`, transformOrigin: '3px 18px', textShadow: '0 1px 2px rgba(0,0,0,.55)' } }}>{pointIndex + 1}</Box>)}</Box><Stack component="ol" spacing={.5} mt={1} sx={{ pl: 3 }}>{visual.points.map(point => <Typography component="li" variant="body2" key={point.label}>{point.label}</Typography>)}</Stack></Box>;
}

const sections: ManualSection[] = [
  { title: 'Getting started and navigation', keywords: 'start navigation menu mobile desktop back dark light mode', content: <><Typography>Use the left navigation on desktop and the bottom navigation plus More menu on mobile. Back returns to the screen or filter you came from. The sun/moon control changes the signed-in application theme.</Typography><Typography mt={1}>Dashboard is the overview; Today, All Tasks, Upcoming, Calendar, Completed and Trash are task views.</Typography></> },
  { title: 'Dashboard and task views', keywords: 'dashboard overdue due today critical blocked waiting cards table refresh filter search', content: <><Typography>Dashboard cards open the matching task list. In a task view, use Priority, Project, Person and Status filters, search by text, choose Smart urgency or another sort, and switch between Table and Cards. Refresh reloads cloud data.</Typography><Typography mt={1}>A light Blocked chip means an incomplete mandatory prerequisite is preventing that task from progressing.</Typography></> },
  { title: 'Creating and editing tasks', keywords: 'create edit title description status priority project responsible due reminder cost save delete trash', content: <><Typography>New task creates a record; opening an existing task first shows read-only details. Select Edit task to change it. The responsible person is accountable for the overall result. Due date, reminder, project, cost, files, links, checklist and prerequisites are optional.</Typography><Typography mt={1}>Delete task moves the task to Trash. It is not shown in active views.</Typography></> },
  { title: 'Checklist or separate task?', keywords: 'checklist person assignee owner responsibility dependency prerequisite blocked required', content: <Stack spacing={1}><Alert severity="info"><strong>Rule of thumb:</strong> a checklist item describes part of one owner’s task; a separate task has its own owner or coordination lifecycle.</Alert><Typography>Keep it as a checklist item when it is a small step, shares the parent task’s responsible person and due date, and does not need its own reminder, files, discussion or reporting.</Typography><Typography>Create a separate task when another person is accountable, it can be delayed independently, it needs a separate deadline/reminder/cost, or other work must wait for it. Link that task as a mandatory prerequisite so the parent becomes blocked until it is complete.</Typography><Typography>Example: “Prepare event” belongs to Davide. “Confirm guest list” can be a checklist item if Davide does it. If Anna owns catering, create “Confirm catering” assigned to Anna and make it a prerequisite of “Prepare event”.</Typography></Stack> },
  { title: 'Dependencies and blocked work', keywords: 'dependencies prerequisite blocking dependency load impact drill down', content: <><Typography>A dependency links a waiting task to a prerequisite. Mandatory incomplete prerequisites mark the waiting task Blocked. Optional dependencies provide context without blocking it.</Typography><Typography mt={1}>Task details let you open each prerequisite and return to the previous task. Dependency load shows who owns prerequisites and which downstream tasks are affected; its cards can be used to drill into the underlying tasks.</Typography></> },
  { title: 'Projects, calendar and costs', keywords: 'project rename edit delete calendar date cost future past month year compare currency graph', content: <><Typography>Projects group tasks and show progress. Use Rename / edit on a project card to change its name, description, or colour. Delete removes the project but preserves its tasks under No project; it also revokes guest and linked-user access to that project.</Typography><Typography mt={1}>Calendar uses task due dates and keeps task counts at the bottom of each day. Costs combine the optional task cost with optional checklist costs; N/A is different from zero. Year and month filters use the completion date for completed costs and the due date for planned costs, so an undated cost appears under All time.</Typography></> },
  { title: 'People, contacts and Recap', keywords: 'people contact phone whatsapp call email recap master link portal share regenerate revoke collaborate permissions', content: <><Typography>People are contacts and responsible parties. Open a person to see their tasks; phone and email actions use the device’s applications. Add to contacts downloads a vCard.</Typography><Typography mt={1}>Adding a person to a project links their existing directory record. It does not assign tasks, create a login, or grant application access. Contact fields stay private unless explicitly shared; removing the project link keeps the person and their tasks.</Typography><Typography mt={1}>Recap creates one revocable live link. Choose assigned work or one project, an optional expiry, and whether the recipient may update assigned checklist items, complete assigned tasks, or comment. Regenerate invalidates the previous link; Revoke disables all access.</Typography></> },
  { title: 'Shared collaboration portal', keywords: 'portal recipient guest verified project checklist complete comment email app linked project project people contacts supervise create edit task manage checklist on behalf', content: <><Typography>A guest can open the link without an account. Reading does not require sign-in; permitted changes require a six-digit code sent to the contact email and remain valid for 30 minutes. Project sharing can independently expose project contacts, task assignments, supervision controls, task authoring, and checklist management. A collaborator can update another contact's work only when that contact is attached to the project, marked supervisable, and the precise checklist or completion permission is enabled.</Typography><Typography mt={1}>Can create and edit tasks is restricted to the selected shared project. New tasks are assigned to the collaborator; they cannot move or delete tasks, change the responsible person, or use editing to bypass the separate completion permission. Can manage checklist items permits adding, renaming, reordering, and removing checklist items. Ticking checklist items remains a separate permission.</Typography><Typography mt={1}>Project people are live references to the owner's People directory. Name and function identify the contact; phone, email, address, and notes appear only when the owner shares each field. Removing someone from Project people does not delete the original contact. Activity history always separates the responsible person from the collaborator who recorded an update. The advanced Manage project contacts permission is off by default and, when explicitly enabled, requires verification before a collaborator can add, edit, or remove project contacts.</Typography><Typography mt={1}>If the recipient also uses Task Tracker, they can select Add to my Task Tracker and sign in with the same invited email. The project then appears under Linked projects, separate from their private workspace. The owner may expire, regenerate, or revoke access at any time.</Typography></> },
  { title: 'Notifications and reminder email', keywords: 'notification email reminder bell permission test quiet hours scheduler trigger', content: <><Typography>Task reminder delivery requires a reminder date/time, an active task, an active account and the corresponding preference. The scheduled reminder service processes due deliveries. Browser notification permission must also be granted by the browser.</Typography><Typography mt={1}>Settings lets you enable or disable live notifications and reminder emails independently. Use the test actions and Diagnostics to verify configuration. Person-portal updates are controlled by the recipient on their shared page.</Typography></> },
  { title: 'Users, access and security', keywords: 'users invite accepted pending revoked admin password security workspace', content: <><Typography>Only the platform administrator sees Users &amp; access and can invite, resend, revoke or disable application users. Invited users receive separate private workspaces and cannot invite others unless explicitly made platform administrators.</Typography><Typography mt={1}>Security contains password/account controls. People records do not grant login access.</Typography></> },
  { title: 'Files, backup and diagnostics', keywords: 'file attachment link upload backup import export diagnostics error warning debug verbose', content: <><Typography>Task files are private and open through time-limited signed links. HTTPS links can also be attached. Backup &amp; import supports portable data transfer; review import previews before applying.</Typography><Typography mt={1}>Diagnostics filters service events by severity and exposes request IDs and downloadable technical detail for troubleshooting.</Typography></> }
];

export function UserManualView() {
  const [query, setQuery] = useState('');
  const normalized = query.trim().toLowerCase();
  const matches = useMemo(() => sections.filter((section) => !normalized || `${section.title} ${section.keywords}`.toLowerCase().includes(normalized)), [normalized]);
  return <Box sx={{ maxWidth: 1000, mx: 'auto' }}>
    <Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h4">User manual</Typography><Chip label={`Connected v${CONNECTED_RELEASE}`} color="primary" variant="outlined"/></Stack>
    <Typography color="text.secondary" mb={2}>Search the guide or open a macro area.</Typography>
    <TextField fullWidth label="Search the manual" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try: checklist, blocked, recap, notifications…" slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search /></InputAdornment> } }} sx={{ mb: 2 }} />
    <Stack direction="row" spacing={1} mb={2} alignItems="center"><Chip label={`${matches.length} section${matches.length === 1 ? '' : 's'}`} /><Typography variant="body2" color="text.secondary">Matching sections open automatically while searching.</Typography></Stack>
    {matches.map((section) => <Accordion key={section.title} defaultExpanded={!!normalized} expanded={normalized ? true : undefined}>
      <AccordionSummary expandIcon={<ExpandMore />}><Typography fontWeight={750}>{section.title}</Typography></AccordionSummary>
      <AccordionDetails>{section.content}<ManualVisual index={sections.indexOf(section)}/></AccordionDetails>
    </Accordion>)}
    {!matches.length && <Alert severity="info">No manual section matches “{query}”. Try a shorter word such as task, person, cost or notification.</Alert>}
  </Box>;
}
