import { useEffect, useMemo, useState } from 'react';
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Chip, IconButton, InputAdornment, Stack, Typography, useMediaQuery } from '@mui/material';
import { ExpandMore, PauseRounded, PlayArrowRounded, ReplayRounded, Search, TouchAppRounded } from '@mui/icons-material';
import { CONNECTED_RELEASE } from '../../../packages/connected-contracts/release';
import { AccessibleTextField as TextField } from './AccessibleTextField';

type ManualSection = { title: string; keywords: string; content: React.ReactNode };
type ManualPoint = { label: string; x: number; y: number; direction: 'up' | 'right' | 'down' | 'left' };
type ManualVisualData = { src: string; mobile?: boolean; points: ManualPoint[] };

const manualVisuals: ManualVisualData[] = [
  { src: '/manual/navigation.png', mobile: true, points: [{ label: 'Theme and account controls', x: 82, y: 4, direction: 'left' }, { label: 'Primary mobile navigation', x: 36, y: 96, direction: 'up' }, { label: 'More menu', x: 88, y: 96, direction: 'up' }] },
  { src: '/manual/tasks.png', points: [{ label: 'Task filters and search', x: 38, y: 24, direction: 'up' }, { label: 'Table, cards and refresh controls', x: 56, y: 34, direction: 'up' }, { label: 'Task cards open their details', x: 49, y: 49, direction: 'down' }] },
  { src: '/manual/task-editor.png', points: [{ label: 'Task identity and description', x: 28, y: 19, direction: 'right' }, { label: 'Status, owner, project and dates', x: 47, y: 46, direction: 'right' }, { label: 'Save task', x: 88, y: 95, direction: 'left' }] },
  { src: '/manual/checklist.png', points: [{ label: 'Checklist section', x: 18, y: 83, direction: 'up' }, { label: 'New checklist item', x: 42, y: 89, direction: 'right' }, { label: 'Add checklist item', x: 82, y: 89, direction: 'left' }] },
  { src: '/manual/dependencies.png', points: [{ label: 'Dependency impact totals', x: 35, y: 36, direction: 'up' }, { label: 'Person-level bottleneck', x: 49, y: 58, direction: 'right' }, { label: 'Open affected work', x: 82, y: 68, direction: 'left' }] },
  { src: '/manual/projects.png', points: [{ label: 'Create a project', x: 88, y: 14, direction: 'left' }, { label: 'Project card and progress', x: 29, y: 31, direction: 'down' }, { label: 'Project actions', x: 28, y: 47, direction: 'up' }] },
  { src: '/manual/people.png', points: [{ label: 'Create a person', x: 88, y: 14, direction: 'left' }, { label: 'Responsibility and progress', x: 29, y: 35, direction: 'down' }, { label: 'Recap and contact actions', x: 29, y: 48, direction: 'up' }] },
  { src: '/manual/projects.png', points: [{ label: 'Linked projects are separate', x: 20, y: 61, direction: 'up' }, { label: 'Open the shared project', x: 40, y: 76, direction: 'right' }, { label: 'Linked access indicator', x: 84, y: 69, direction: 'left' }] },
  { src: '/manual/settings.png', points: [{ label: 'Live notification controls', x: 26, y: 27, direction: 'right' }, { label: 'Reminder email controls', x: 28, y: 49, direction: 'right' }, { label: 'Notification readiness', x: 31, y: 72, direction: 'right' }] },
  { src: '/manual/access.png', points: [{ label: 'User and delivery summary', x: 29, y: 31, direction: 'right' }, { label: 'Invite a user', x: 50, y: 43, direction: 'up' }, { label: 'Expandable access groups', x: 33, y: 65, direction: 'right' }] },
  { src: '/manual/diagnostics.png', points: [{ label: 'Refresh or download diagnostics', x: 84, y: 17, direction: 'left' }, { label: 'Connected service health', x: 48, y: 43, direction: 'down' }, { label: 'Recent service events', x: 50, y: 76, direction: 'up' }] }
];

function ManualVisual({ index, active }: { index: number; active: boolean }) {
  const visual = manualVisuals[index];
  const reduceMotion = useMediaQuery('(prefers-reduced-motion: reduce)');
  const [step, setStep] = useState(0);
  const [playing, setPlaying] = useState(!reduceMotion);
  useEffect(() => {
    if (!active || !playing || reduceMotion) return;
    const timer = window.setInterval(() => setStep(value => (value + 1) % visual.points.length), 2600);
    return () => window.clearInterval(timer);
  }, [active, playing, reduceMotion, visual.points.length]);
  useEffect(() => {
    if (active) setStep(0);
  }, [active]);
  const point = visual.points[step];
  return <Box mt={2}>
    <Stack direction="row" justifyContent="space-between" alignItems="center" mb={1}>
      <Box><Typography fontWeight={700}>Animated walkthrough</Typography><Typography variant="caption" color="text.secondary">Step {step + 1} of {visual.points.length} · {point.label}</Typography></Box>
      <Stack direction="row" spacing={.25}>
        {!reduceMotion && <IconButton size="small" aria-label={playing ? 'Pause walkthrough' : 'Play walkthrough'} onClick={() => setPlaying(value => !value)}>{playing ? <PauseRounded/> : <PlayArrowRounded/>}</IconButton>}
        <IconButton size="small" aria-label="Replay walkthrough" onClick={() => { setStep(0); setPlaying(!reduceMotion); }}><ReplayRounded/></IconButton>
      </Stack>
    </Stack>
    <Box sx={{ position: 'relative', width: visual.mobile ? 'min(100%, 390px)' : 'min(100%, 683px)', aspectRatio: visual.mobile ? '390 / 844' : '1180 / 760', mx: 'auto', borderRadius: 2, overflow: 'hidden', border: 1, borderColor: 'divider', bgcolor: 'background.default' }}>
      <Box component="img" src={visual.src} alt={`Task Tracker walkthrough: ${point.label}`} sx={{ position: 'absolute', inset: 0, display: 'block', width: '100%', height: '100%', objectFit: 'fill', transform: active && !reduceMotion ? 'scale(1.035)' : 'scale(1)', transformOrigin: `${point.x}% ${point.y}%`, transition: 'transform-origin 500ms ease, transform 500ms ease' }}/>
      <TouchAppRounded aria-hidden key={`${index}-${step}`} sx={{ position: 'absolute', top: `${point.y}%`, left: `${point.x}%`, color: 'common.white', fontSize: { xs: 34, sm: 42 }, zIndex: 2, filter: 'drop-shadow(0 2px 2px rgba(0,0,0,.9)) drop-shadow(0 0 5px #60a5fa)', animation: reduceMotion ? 'none' : 'manualTap 1.35s ease-in-out infinite', '@keyframes manualTap': { '0%, 35%, 100%': { transform: 'translate(-50%,-58%) scale(1)' }, '52%': { transform: 'translate(-50%,-46%) scale(.92)' }, '64%': { transform: 'translate(-50%,-50%) scale(.96)' } } }}/>
    </Box>
    <Box sx={{ width: visual.mobile ? 'min(100%, 390px)' : 'min(100%, 683px)', mx: 'auto', mt: 1, p: 1, borderRadius: 2, border: 1, borderColor: 'divider', bgcolor: 'background.default' }}>
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: `repeat(${visual.points.length}, minmax(0, 1fr))` }, gap: .75 }}>
        {visual.points.map((entry, current) => <Button key={entry.label} aria-label={`Show step ${current + 1}: ${entry.label}`} onClick={() => { setStep(current); setPlaying(false); }} variant={current === step ? 'contained' : 'outlined'} sx={{ minWidth: 0, minHeight: { xs: 46, sm: 58 }, px: 1, py: .75, borderRadius: 1.5, justifyContent: 'flex-start', alignItems: 'center', gap: .75, textTransform: 'none', lineHeight: 1.15 }}><Box component="span" sx={{ flex: '0 0 auto', width: 25, height: 25, borderRadius: '50%', display: 'grid', placeItems: 'center', bgcolor: current === step ? 'common.white' : 'action.selected', color: current === step ? 'primary.main' : 'text.primary', fontWeight: 900 }}>{current + 1}</Box><Typography component="span" variant="caption" fontWeight={750} textAlign="left">{entry.label}</Typography></Button>)}
      </Box>
    </Box>
  </Box>;
}

const sections: ManualSection[] = [
  { title: 'Getting started and navigation', keywords: 'start navigation menu mobile desktop back dark light mode', content: <><Typography>Use the left navigation on desktop and the bottom navigation plus More menu on mobile. Back returns to the screen or filter you came from. The sun/moon control changes the signed-in application theme.</Typography><Typography mt={1}>Dashboard is the overview; Today, All Tasks, Upcoming, Calendar, Completed and Trash are task views.</Typography></> },
  { title: 'Dashboard, Today and deadline pressure', keywords: 'dashboard collapsed expand overdue due today checklist pressure daily weekly heavy score heatmap drill down', content: <Stack spacing={1}><Typography>The six headline task metrics remain visible. The analytical Dashboard cards—Overall workload, Progress by project, Checklist attention, Deadline pressure and Total cost—start collapsed. Select a card heading to expand or collapse it independently.</Typography><Typography>Task cards keep task counts separate from the Checklist due today and Checklist overdue metrics. Select either checklist metric to inspect the contributing checklist items.</Typography><Typography>Today is intentionally focused: it keeps parent tasks under Tasks due today and adds separate overdue and due-today checklist sections. Deadline Pressure is available on Dashboard and Calendar, not Today. Completing a checklist item in Today updates progress immediately; it may automatically complete its parent only when that option is enabled and every required condition is satisfied.</Typography><Typography>Deadline pressure combines active task and incomplete checklist deadlines. Daily covers 28 days and Weekly covers 12 weeks. A normal task scores 2, high 3, critical 5, and a checklist item 1, with limited parent-priority bonuses. Carried-over overdue work adds 2; a blocked parent adds 1 only once per period.</Typography><Typography>Light, Moderate, Heavy and Very heavy are relative to the non-empty periods in the visible horizon. Percentiles are used with four or more non-empty periods; smaller samples use a deterministic comparison to their median. Empty periods are No deadlines. Select any period to see counts, every contributor and its score contribution.</Typography></Stack> },
  { title: 'Creating and editing tasks', keywords: 'create edit title description status priority project responsible due reminder cost save delete trash', content: <><Typography>New task creates a record; opening an existing task first shows read-only details. Select Edit task to change it. The responsible person is accountable for the overall result. Due date, reminder, project, cost, files, links, checklist and prerequisites are optional.</Typography><Typography mt={1}>Delete task moves the task to Trash. It is not shown in active views.</Typography></> },
  { title: 'Checklist or separate task?', keywords: 'checklist date today overdue auto complete person assignee owner responsibility dependency prerequisite blocked required optional', content: <Stack spacing={1}><Alert severity="info"><strong>Date rule:</strong> a checklist date never changes the parent task date. Both remain independent deadlines.</Alert><Typography>Keep work as a checklist item when it is a step owned with the parent task. Required and optional dated items both appear in checklist attention; Required controls completion rules, not deadline visibility.</Typography><Typography>Incomplete dated items appear in Today when due or overdue, in Dashboard checklist metrics, Calendar, and Deadline Pressure. The Calendar groups several items under one parent-task card and ignores completed items. Complete an item directly from Today or a pressure drill-down.</Typography><Typography>Create a separate task when another person is accountable, it can be delayed independently, it needs its own reminder, files or discussion, or other work must wait for it. Link that task as a mandatory prerequisite so the parent becomes blocked until complete.</Typography></Stack> },
  { title: 'Dependencies and blocked work', keywords: 'dependencies prerequisite blocking dependency load impact drill down', content: <><Typography>A dependency links a waiting task to a prerequisite. Mandatory incomplete prerequisites mark the waiting task Blocked. Optional dependencies provide context without blocking it.</Typography><Typography mt={1}>Task details let you open each prerequisite and return to the previous task. Dependency load shows who owns prerequisites and which downstream tasks are affected; its cards can be used to drill into the underlying tasks.</Typography></> },
  { title: 'Projects, calendar and costs', keywords: 'project rename edit delete calendar pressure date cost future past month year compare currency graph paid timezone', content: <><Typography>Projects group tasks and show progress. Use Rename / edit on a project card to change its name, description, or colour. Delete removes the project but preserves its tasks under No project; it also revokes guest and linked-user access to that project.</Typography><Typography mt={1}>Calendar uses task due dates and keeps its count as unique parent-task cards. Incomplete checklist dates can place the parent card on another day without changing its task date. A separate pressure dot uses the same canonical daily pressure data as Dashboard; the legend explains the colours.</Typography><Typography mt={1}>Task and checklist dates are date-only values and are compared using the browser’s local date and configured notification timezone so they do not shift through UTC conversion. Weeks begin Monday because no separate first-day-of-week preference is currently available.</Typography><Typography mt={1}>Costs combine the optional task cost with optional checklist costs; cost dates are independent and never contribute to Deadline Pressure.</Typography></> },
  { title: 'People, contacts and Recap', keywords: 'people contact phone whatsapp call email recap master link portal share regenerate revoke collaborate permissions', content: <><Typography>People are contacts and responsible parties. Open a person to see their tasks; phone and email actions use the device’s applications. Add to contacts downloads a vCard.</Typography><Typography mt={1}>Adding a person to a project links their existing directory record. It does not assign tasks, create a login, or grant application access. Contact fields stay private unless explicitly shared; removing the project link keeps the person and their tasks.</Typography><Typography mt={1}>Recap creates one revocable live link. Choose assigned work or one project, an optional expiry, and whether the recipient may update assigned checklist items, complete assigned tasks, or comment. Regenerate invalidates the previous link; Revoke disables all access.</Typography></> },
  { title: 'Shared collaboration portal', keywords: 'portal recipient guest verified project checklist complete comment email app linked project project people contacts supervise create edit task manage checklist on behalf install pwa notification iphone ipad android chrome edge', content: <><Typography>A guest can open the link without an account. Reading does not require sign-in; permitted changes require a six-digit code sent to the contact email and remain valid for 30 minutes. Project sharing can independently expose project contacts, task assignments, supervision controls, task authoring, and checklist management. A collaborator can update another contact's work only when that contact is attached to the project, marked supervisable, and the precise checklist or completion permission is enabled.</Typography><Typography mt={1}>The Updates card guides recipients through installation before notification permission on installable browsers. Android Chrome, desktop Chrome, and Edge use their native installation confirmation. On iPhone and iPad, open the link in Safari and follow Share → Add to Home Screen. Task Tracker remembers the shared link during installation and returns the installed app to that same portal. The portal then offers Enable notifications; the Browser notifications switch appears after permission is granted. Installed applications never show the installation prompt again. Browsers without an installation facility retain direct browser-notification setup.</Typography><Typography mt={1}>Can create and edit tasks is restricted to the selected shared project. New tasks are assigned to the collaborator; they cannot move or delete tasks, change the responsible person, or use editing to bypass the separate completion permission. Can manage checklist items permits adding, renaming, reordering, and removing checklist items. Ticking checklist items remains a separate permission.</Typography><Typography mt={1}>Project people are live references to the owner's People directory. Name and function identify the contact; phone, email, address, and notes appear only when the owner shares each field. Removing someone from Project people does not delete the original contact. Activity history always separates the responsible person from the collaborator who recorded an update. The advanced Manage project contacts permission is off by default and, when explicitly enabled, requires verification before a collaborator can add, edit, or remove project contacts.</Typography><Typography mt={1}>If the recipient also uses Task Tracker, they can select Add to my Task Tracker and sign in with the same invited email. The project then appears under Linked projects, separate from their private workspace. The owner may expire, regenerate, or revoke access at any time.</Typography></> },
  { title: 'Notifications, installation and reminder email', keywords: 'notification install pwa home screen iphone ipad android checklist recurring repeat daily weekly monthly email reminder bell permission test quiet hours scheduler trigger', content: <><Typography>Task reminder delivery requires a reminder date/time, an active task, an active account and the corresponding preference. A reminder can run once or repeat daily, weekly, or monthly at a chosen interval until the task closes.</Typography><Typography mt={1}>Settings shows installation, browser permission, device subscription, provider, and delivery readiness separately. On supported Chrome and Edge browsers, Install Task Tracker opens the browser’s native confirmation dialog. A website cannot install itself without that confirmation.</Typography><Typography mt={1}>On iPhone or iPad, open Task Tracker in Safari, use Share → Add to Home Screen, launch the installed app, and then select Enable notifications in Settings. Installation and notification permission are separate user decisions. Desktop browsers may support notifications without installation.</Typography><Typography mt={1}>The existing scheduler also creates one idempotent in-app notification for each incomplete checklist item due today, using each user’s configured timezone. Checklist push and email delivery are not active in this release; task reminder push/email behavior is unchanged. Overdue checklist items remain visible in Today until resolved.</Typography><Typography mt={1}>Use Settings test actions and Diagnostics to verify providers and scheduler health.</Typography></> },
  { title: 'Users, access and security', keywords: 'users invite accepted pending revoked admin password username display name security workspace', content: <><Typography>Only the platform administrator sees Users &amp; access and can invite, resend, revoke or disable application users. During invitation acceptance, a new user chooses both a password and a display name. Email remains the sign-in identifier; the display name is how the user is shown in Task Tracker.</Typography><Typography mt={1}>Invited users receive separate private workspaces and cannot invite others unless explicitly made platform administrators. Use Security to change your username/display name or password and to sign out all sessions. People records do not grant login access.</Typography></> },
  { title: 'Files, backup, restore and diagnostics', keywords: 'file attachment link upload backup import restore disaster recovery export diagnostics error warning debug verbose', content: <><Typography>Task files are private and open through time-limited signed links. HTTPS links can also be attached. Download Connected JSON backups regularly; format v3 includes a SHA-256 checksum and record counts.</Typography><Typography mt={1}>Workspace owners can validate a Connected backup without changing data, then restore it into an empty workspace or replace current data. Replace uses one database transaction, downloads a portable pre-restore safety backup, stores an internal safety snapshot, and requires the exact confirmation phrase. A failed record rolls back the whole restore.</Typography><Typography mt={1}>Restores rewrite workspace and user ownership to the authenticated workspace owner. They never restore credentials, sessions, push subscriptions, guest links, or notification delivery history. Attachment files are not yet included; to prevent data loss, replacement is blocked while active attachments exist. Open reminders are delayed briefly to prevent an immediate notification flood.</Typography><Typography mt={1}>Diagnostics filters service events by severity and exposes request IDs and downloadable technical detail for troubleshooting. Automated scheduled restore verification and attachment ZIP archives remain separate disaster-recovery phases.</Typography></> }
];

export function UserManualView() {
  const [query, setQuery] = useState('');
  const [expanded, setExpanded] = useState<string | false>(false);
  const normalized = query.trim().toLowerCase();
  const matches = useMemo(() => sections.filter((section) => !normalized || `${section.title} ${section.keywords}`.toLowerCase().includes(normalized)), [normalized]);
  return <Box sx={{ maxWidth: 1000, mx: 'auto' }}>
    <Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h4">User manual</Typography><Chip label={`Connected v${CONNECTED_RELEASE}`} color="primary" variant="outlined"/></Stack>
    <Typography color="text.secondary" mb={2}>Search the guide or open a macro area.</Typography>
    <TextField fullWidth label="Search the manual" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try: checklist, blocked, recap, notifications…" slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search /></InputAdornment> } }} sx={{ mb: 2 }} />
    <Stack direction="row" spacing={1} mb={2} alignItems="center"><Chip label={`${matches.length} section${matches.length === 1 ? '' : 's'}`} /><Typography variant="body2" color="text.secondary">Matching sections open automatically while searching.</Typography></Stack>
    {matches.map((section) => <Accordion key={section.title} expanded={normalized ? true : expanded === section.title} onChange={(_, open) => setExpanded(open ? section.title : false)}>
      <AccordionSummary expandIcon={<ExpandMore />}><Typography fontWeight={750}>{section.title}</Typography></AccordionSummary>
      <AccordionDetails>{section.content}<ManualVisual index={sections.indexOf(section)} active={Boolean(normalized) || expanded === section.title}/></AccordionDetails>
    </Accordion>)}
    {!matches.length && <Alert severity="info">No manual section matches “{query}”. Try a shorter word such as task, person, cost or notification.</Alert>}
  </Box>;
}
