const {contextBridge}=require('electron');

const tasks=[
 {id:'t1',title:'Prepare customer presentation',description:'Finalize the technical story, screenshots, and commercial handoff.',status:'in_progress',priority:'critical',startDate:'2026-09-08',dueDate:'2026-09-10',dueTime:'16:00',createdAt:'2026-09-05T08:30:00Z',updatedAt:'2026-09-10T09:45:00Z',projectId:'p1',responsiblePersonId:'u1',tags:['customer','presentation'],notes:'Review final slides with the account team.',progressMode:'weighted',manualProgress:0,archived:false,attachments:[],recurrence:null,reminder:null,links:[],blockedReasons:[],calculatedProgress:67,urgencyScore:98,checklist:[{id:'c1',taskId:'t1',description:'Confirm agenda',completed:true,weight:1,notes:'',position:0,required:true},{id:'c2',taskId:'t1',description:'Finish product slides',completed:true,weight:2,notes:'',position:1,required:true},{id:'c3',taskId:'t1',description:'Rehearse demonstration',completed:false,weight:2,notes:'',position:2,required:true}]},
 {id:'t2',title:'Renew home insurance',description:'Compare the renewal quotation and confirm the selected coverage.',status:'not_started',priority:'high',startDate:'2026-09-09',dueDate:'2026-09-12',createdAt:'2026-09-06T12:00:00Z',updatedAt:'2026-09-09T15:20:00Z',projectId:'p2',tags:['finance','home'],notes:'',progressMode:'automatic',manualProgress:0,archived:false,attachments:[],recurrence:null,reminder:null,links:[],blockedReasons:[],calculatedProgress:0,urgencyScore:76,checklist:[{id:'c4',taskId:'t2',description:'Review quotation',completed:false,weight:1,notes:'',position:0,required:true},{id:'c5',taskId:'t2',description:'Confirm payment',completed:false,weight:1,notes:'',position:1,required:true}]},
 {id:'t3',title:'Order replacement component',description:'Place the order once the supplier confirms the revised lead time.',status:'blocked',priority:'medium',startDate:'2026-09-08',dueDate:'2026-09-15',createdAt:'2026-09-03T10:00:00Z',updatedAt:'2026-09-10T07:10:00Z',projectId:'p1',responsiblePersonId:'u2',tags:['supplier'],notes:'Waiting for written confirmation.',progressMode:'automatic',manualProgress:0,archived:false,attachments:[],recurrence:null,reminder:null,links:[{id:'l1',fromTaskId:'t3',toTaskId:'t4',type:'blocked_by',mandatory:true}],blockedReasons:['Supplier lead-time confirmation'],calculatedProgress:50,urgencyScore:65,checklist:[{id:'c6',taskId:'t3',description:'Request quotation',completed:true,weight:1,notes:'',position:0,required:true},{id:'c7',taskId:'t3',description:'Submit purchase order',completed:false,weight:1,notes:'',position:1,required:true}]},
 {id:'t4',title:'Supplier lead-time confirmation',description:'Obtain written confirmation of delivery before releasing the order.',status:'waiting',priority:'high',startDate:'2026-09-07',dueDate:'2026-09-11',createdAt:'2026-09-04T09:00:00Z',updatedAt:'2026-09-10T11:30:00Z',projectId:'p1',responsiblePersonId:'u2',tags:['supplier','waiting'],notes:'Follow-up sent this morning.',progressMode:'manual',manualProgress:40,archived:false,attachments:[],recurrence:null,reminder:null,links:[],blockedReasons:[],calculatedProgress:40,urgencyScore:72,checklist:[]},
 {id:'t5',title:'Schedule annual boiler service',description:'Agree a service date with the technician.',status:'not_started',priority:'low',startDate:'2026-09-10',dueDate:'2026-09-25',createdAt:'2026-09-10T06:30:00Z',updatedAt:'2026-09-10T06:30:00Z',projectId:'p2',responsiblePersonId:'u3',tags:['home'],notes:'',progressMode:'automatic',manualProgress:0,archived:false,attachments:[],recurrence:{frequency:'yearly',interval:1,generation:'schedule'},reminder:null,links:[],blockedReasons:[],calculatedProgress:0,urgencyScore:22,checklist:[{id:'c8',taskId:'t5',description:'Call technician',completed:false,weight:1,notes:'',position:0,required:true}]},
 {id:'t6',title:'Archive completed project files',description:'Move final documentation into the project archive.',status:'completed',priority:'none',startDate:'2026-09-01',dueDate:'2026-09-08',createdAt:'2026-09-01T08:00:00Z',updatedAt:'2026-09-08T14:00:00Z',completedAt:'2026-09-08T14:00:00Z',projectId:'p1',tags:['documentation'],notes:'',progressMode:'automatic',manualProgress:0,archived:false,attachments:[],recurrence:null,reminder:null,links:[],blockedReasons:[],calculatedProgress:100,urgencyScore:0,checklist:[{id:'c9',taskId:'t6',description:'Archive files',completed:true,weight:1,notes:'',position:0,required:true}]}
];
const people=[
 {id:'u1',fullName:'Elena Rossi',company:'Northstar Industries',role:'Account Manager',phone:'+41 79 555 01 12',email:'elena.rossi@example.com',address:'Lugano, Switzerland',website:'https://example.com',preferredContact:'Email',notes:'Customer presentation owner',tags:['customer'],createdAt:'2026-09-01T08:00:00Z',updatedAt:'2026-09-09T08:00:00Z'},
 {id:'u2',fullName:'Marco Bianchi',company:'Precision Components SA',role:'Supplier Contact',phone:'+41 91 555 31 22',email:'marco.bianchi@example.com',address:'Mendrisio, Switzerland',website:'https://example.com',preferredContact:'Phone',notes:'',tags:['supplier'],createdAt:'2026-09-01T08:00:00Z',updatedAt:'2026-09-09T08:00:00Z'},
 {id:'u3',fullName:'Roberto Conti',company:'RC Home Services',role:'Technician',phone:'+39 333 555 0198',email:'roberto.conti@example.com',address:'Como, Italy',website:'',preferredContact:'WhatsApp',notes:'Annual service contact',tags:['home'],createdAt:'2026-09-01T08:00:00Z',updatedAt:'2026-09-09T08:00:00Z'}
];
const projects=[{id:'p1',name:'Customer Delivery',color:'#2563eb',description:'Customer-facing work and supplier coordination.',archived:false},{id:'p2',name:'Home Administration',color:'#16a34a',description:'Household maintenance, insurance, and recurring obligations.',archived:false}];
let settings={theme:'light',defaultView:'dashboard',defaultSort:'smart',defaultPriority:'medium',dateFormat:'locale',firstDay:1,notifications:true,quietStart:'22:00',quietEnd:'07:00',startWithWindows:false,backupFolder:'',backupFrequency:'weekly',backupRetention:10,logLevel:'info',logRetentionDays:30,trashRetentionDays:30};
const health=Object.fromEntries(['gateway','tasks','dependencies','people','reminders','backup','logs','data'].map((service,index)=>[service,{service,status:'ok',version:'1.0.1',uptime:184+index*3}]));
const dashboard={counts:{overdue:1,today:1,next7:4,critical:1,blocked:1,waiting:1,recentCompleted:1,active:5},needsAttention:tasks.slice(0,4),recent:tasks.slice(0,4),recentlyUnblocked:[],projectProgress:[{id:'p1',name:'Customer Delivery',progress:52,active:4},{id:'p2',name:'Home Administration',progress:0,active:2}],workload:[{date:'2026-09-10',count:1},{date:'2026-09-11',count:1},{date:'2026-09-12',count:1},{date:'2026-09-13',count:0},{date:'2026-09-14',count:0},{date:'2026-09-15',count:1},{date:'2026-09-16',count:0}],overallProgress:31};
const logs=[{id:'g1',timestamp:'2026-09-10T12:01:02Z',level:'info',module:'supervisor:data',message:'Data service ready',details:''},{id:'g2',timestamp:'2026-09-10T12:01:03Z',level:'info',module:'supervisor:tasks',message:'Task service ready',details:''},{id:'g3',timestamp:'2026-09-10T12:01:04Z',level:'info',module:'supervisor:gateway',message:'API gateway ready',details:''}];
const page=(q={})=>{let items=[...tasks];if(q.view==='completed')items=items.filter(t=>t.status==='completed');else if(q.view==='today')items=items.filter(t=>t.dueDate<='2026-09-10'&&t.status!=='completed');else if(q.view==='trash')items=[];else if(q.view==='upcoming')items=items.filter(t=>t.dueDate>'2026-09-10'&&t.status!=='completed');else items=items.filter(t=>t.status!=='completed');if(q.search)items=items.filter(t=>(t.title+' '+t.description).toLowerCase().includes(q.search.toLowerCase()));if(q.projectId)items=items.filter(t=>t.projectId===q.projectId);if(q.responsiblePersonId)items=items.filter(t=>t.responsiblePersonId===q.responsiblePersonId);if(q.priorities?.length)items=items.filter(t=>q.priorities.includes(t.priority));if(q.statuses?.length)items=items.filter(t=>q.statuses.includes(t.status));if(q.due==='overdue')items=items.filter(t=>t.dueDate<'2026-09-10');if(q.due==='today')items=items.filter(t=>t.dueDate==='2026-09-10');if(q.due==='next7')items=items.filter(t=>t.dueDate>'2026-09-10'&&t.dueDate<='2026-09-17');if(q.dueDate)items=items.filter(t=>t.dueDate===q.dueDate);if(q.blocked!==undefined)items=items.filter(t=>Boolean(t.blockedReasons?.length)===q.blocked);return{items,total:items.length,page:1,pageSize:500}};
const api={
 tasks:{list:async q=>page(q),get:async id=>tasks.find(t=>t.id===id),save:async t=>({...tasks[0],...t,id:t.id||'new'}),remove:async()=>{},restore:async()=>{},bulk:async()=>{},toggleChecklist:async()=>tasks[0],candidates:async()=>({items:tasks.slice(0,4),total:4,page:1,pageSize:25}),createPrerequisite:async()=>({waitingTask:tasks[2],prerequisite:tasks[3]}),convertChecklist:async()=>({waitingTask:tasks[2],prerequisite:tasks[3]})},
 people:{list:async()=>people,save:async p=>({...people[0],...p}),remove:async()=>{}},projects:{list:async()=>projects,save:async p=>({...projects[0],...p}),remove:async()=>{}},
 dashboard:async()=>dashboard,workloads:async()=>({projects:[{projectId:'p1',totalTasks:4,completedTasks:1,activeTasks:3,progress:64},{projectId:'p2',totalTasks:2,completedTasks:0,activeTasks:2,progress:0}],people:[{personId:'u1',totalTasks:1,completedTasks:0,activeTasks:1,progress:67},{personId:'u2',totalTasks:2,completedTasks:0,activeTasks:2,progress:45},{personId:'u3',totalTasks:1,completedTasks:0,activeTasks:1,progress:0}]}),bottlenecks:async()=>({generatedAt:new Date().toISOString(),formula:'10 × affected tasks + 25 × affected projects + 15 × overdue prerequisites + 20 × critical tasks + 10 × high-priority tasks + 2 × capped dependency depth',people:[{personId:'u2',personName:'Marco Bianchi',blockingPrerequisites:1,affectedTasks:2,affectedProjects:1,overduePrerequisites:1,criticalHighImpact:1,impactScore:82,scoreBreakdown:{affectedTasks:20,affectedProjects:25,overduePrerequisites:15,criticalTasks:20,highPriorityTasks:0,indirectDepth:2},relationships:[{prerequisite:{id:'t4',title:tasks[3].title,status:'waiting',priority:'high',projectId:'p1',projectName:'Customer Delivery',responsiblePersonId:'u2',responsiblePersonName:'Marco Bianchi',dueDate:'2026-09-11'},affectedTask:{id:'t3',title:tasks[2].title,status:'blocked',priority:'medium',projectId:'p1',projectName:'Customer Delivery',responsiblePersonId:'u2',responsiblePersonName:'Marco Bianchi',dueDate:'2026-09-15'},depth:1,direct:true,path:[{id:'t4',title:tasks[3].title},{id:'t3',title:tasks[2].title}],sharedDependency:false,otherResponsiblePeople:[],daysOverdue:3}]}]}),calendar:{range:async(start,end)=>{const days=[];const cursor=new Date(start+'T12:00:00'),last=new Date(end+'T12:00:00');while(cursor<=last){const date=cursor.toISOString().slice(0,10),matches=tasks.filter(t=>t.dueDate===date).map(task=>({task,projectName:projects.find(p=>p.id===task.projectId)?.name||'No project',responsiblePersonName:people.find(p=>p.id===task.responsiblePersonId)?.fullName||'Unassigned',reasons:['due'],relevantTime:task.dueTime,blocked:Boolean(task.blockedReasons.length),overdue:false,severity:task.priority==='critical'?'red':task.priority==='high'?'orange':task.status==='completed'?'green':'blue'}));days.push({date,severity:matches[0]?.severity||'neutral',counts:{total:matches.length,overdue:0,critical:matches.filter(x=>x.task.priority==='critical').length,high:matches.filter(x=>x.task.priority==='high').length,completed:matches.filter(x=>x.task.status==='completed').length},tasks:matches});cursor.setDate(cursor.getDate()+1)}return{start,end,generatedAt:new Date().toISOString(),days}}},reminders:{center:async()=>[],snooze:async()=>{},dismiss:async()=>{}},rendererDiagnostic:async()=>{},activities:async()=>[{id:'a1',taskId:'t1',action:'updated',summary:'Progress changed to 67%',createdAt:'2026-09-10T09:45:00Z'},{id:'a2',taskId:'t1',action:'created',summary:'Task created',createdAt:'2026-09-05T08:30:00Z'}],logs:async()=>logs,clearLogs:async()=>{},
 settings:{get:async()=>settings,save:async v=>(settings={...settings,...v})},backup:{create:async()=>'C:\\Users\\Dave\\AppData\\Roaming\\PriorityDesk\\backups\\backup.zip',validate:async()=>({valid:true,warnings:[],errors:[],path:'backup.zip'}),restore:async()=>({message:'Restored',warnings:[]})},
 files:{pick:async()=>null,open:async()=>{},addAttachment:async()=>null},export:async()=>'',importData:async()=>({preview:{valid:0,total:0,errors:[]},token:'demo'}),applyImport:async()=>({message:'Imported'}),
 app:{version:async()=>'1.3.1',notify:async()=>{},health:async()=>health,supervisorHealth:async()=>[],restartService:async()=>{},restartApplication:async()=>{}}
};
contextBridge.exposeInMainWorld('priorityDesk',api);
