begin;
create extension if not exists pgcrypto;
create type public.workspace_role as enum ('owner','admin','member','viewer');
create type public.task_status as enum ('not_started','in_progress','waiting','blocked','completed','cancelled','archived');
create type public.task_priority as enum ('critical','high','medium','low','none');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text,display_name text not null default '',timezone text not null default 'UTC',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version int not null default 1);
create table public.workspaces(id uuid primary key default gen_random_uuid(),name text not null,plan text not null default 'free',product_edition text not null default 'connected',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),version int not null default 1);
create table public.workspace_members(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role public.workspace_role not null default 'member',created_at timestamptz not null default now(),removed_at timestamptz,unique(workspace_id,user_id));
create table public.projects(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,name text not null,color text not null default '#2563eb',description text not null default '',archived boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1,unique(workspace_id,name));
create table public.people(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,full_name text not null,company text not null default '',role text not null default '',phone text not null default '',email text not null default '',address text not null default '',website text not null default '',preferred_contact text not null default '',notes text not null default '',tags jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1);
create table public.tasks(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,title text not null check(length(title) between 1 and 500),description text not null default '',status public.task_status not null default 'not_started',priority public.task_priority not null default 'medium',start_date date,due_date date,due_time time,completed_at timestamptz,project_id uuid references public.projects(id) on delete set null,responsible_person_id uuid references public.people(id) on delete set null,tags jsonb not null default '[]',notes text not null default '',progress_mode text not null default 'automatic',manual_progress int not null default 0 check(manual_progress between 0 and 100),calculated_progress int not null default 0 check(calculated_progress between 0 and 100),blocked boolean not null default false,archived boolean not null default false,deleted_at timestamptz,reminder_at timestamptz,recurrence jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),version int not null default 1);
create table public.checklist_items(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,task_id uuid not null references public.tasks(id) on delete cascade,description text not null,completed boolean not null default false,required boolean not null default true,responsible_person_id uuid references public.people(id) on delete set null,due_date date,weight numeric not null default 1,position int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1);
create table public.task_dependencies(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,waiting_task_id uuid not null references public.tasks(id) on delete cascade,prerequisite_task_id uuid not null references public.tasks(id) on delete cascade,mandatory boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1,check(waiting_task_id<>prerequisite_task_id),unique(waiting_task_id,prerequisite_task_id));
create table public.task_people(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,task_id uuid not null references public.tasks(id) on delete cascade,person_id uuid not null references public.people(id) on delete cascade,relationship text not null default 'contact',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1,unique(task_id,person_id,relationship));
create table public.recurrence_rules(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,task_id uuid not null references public.tasks(id) on delete cascade,frequency text not null,interval_count int not null default 1,weekdays int[],generation text not null default 'completion',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1);
create table public.reminders(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,task_id uuid not null references public.tasks(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,scheduled_at timestamptz not null,next_attempt_at timestamptz not null,snoozed_until timestamptz,dismissed boolean not null default false,claimed_at timestamptz,attempt_count int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1);
create table public.push_subscriptions(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,endpoint text not null,p256dh text not null,auth text not null,expiration_time bigint,device_label text,disabled boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version int not null default 1,unique(user_id,endpoint));
create table public.notification_preferences(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,email_enabled boolean not null default true,push_enabled boolean not null default true,reminder boolean not null default true,due_today boolean not null default true,overdue boolean not null default true,daily_summary boolean not null default false,timezone text not null default 'UTC',quiet_start time not null default '22:00',quiet_end time not null default '07:00',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version int not null default 1,unique(workspace_id,user_id));
create table public.notification_deliveries(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,task_id uuid references public.tasks(id) on delete set null,reminder_id uuid references public.reminders(id) on delete set null,kind text not null,idempotency_key text not null,status text not null default 'pending',attempt_count int not null default 0,last_error_code text,delivered_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version int not null default 1,unique(workspace_id,idempotency_key));
create table public.activities(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,task_id uuid references public.tasks(id) on delete cascade,event_type text not null,summary text not null,details jsonb,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1);
create table public.attachments(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,task_id uuid references public.tasks(id) on delete cascade,storage_path text not null,mime_type text not null,size_bytes bigint not null,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1);
create table public.exports(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,kind text not null,status text not null default 'ready',created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),deleted_at timestamptz,version int not null default 1);
create table public.audit_events(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,level text not null default 'info',service text not null,event_type text not null,request_id text,summary text not null,details jsonb,created_at timestamptz not null default now());
create table public.imports(id uuid primary key,workspace_id uuid not null references public.workspaces(id) on delete cascade,status text not null,source_version text,counts jsonb not null default '{}',warnings jsonb not null default '[]',safety_snapshot jsonb,created_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_at timestamptz not null default now(),version int not null default 1,unique(workspace_id,id));
create table public.schema_versions(version int primary key,applied_at timestamptz not null default now());
create table public.entitlements(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,product_edition text not null default 'connected',plan text not null default 'owner_free',license_status text not null default 'active',trial_start timestamptz,trial_end timestamptz,provider_reference text,max_users int,maximum_storage_bytes bigint,enabled_features jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version int not null default 1,unique(workspace_id,product_edition));

create index tasks_active_workspace on public.tasks(workspace_id,status,due_date) where deleted_at is null and archived=false;
create index tasks_project on public.tasks(workspace_id,project_id,status);create index tasks_person on public.tasks(workspace_id,responsible_person_id,status);
create index checklist_completion on public.checklist_items(task_id,required,completed) where deleted_at is null;
create index dependencies_waiting on public.task_dependencies(workspace_id,waiting_task_id) where deleted_at is null;create index dependencies_prerequisite on public.task_dependencies(workspace_id,prerequisite_task_id) where deleted_at is null;
create index reminders_due on public.reminders(workspace_id,next_attempt_at) where dismissed=false and deleted_at is null;
create index delivery_idempotency on public.notification_deliveries(workspace_id,idempotency_key);create index push_owner on public.push_subscriptions(workspace_id,user_id) where disabled=false;
create index audit_recent on public.audit_events(workspace_id,created_at desc);

create or replace function public.is_workspace_member(w uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from workspace_members where workspace_id=w and user_id=auth.uid() and removed_at is null)$$;
create or replace function public.workspace_role_for(w uuid) returns public.workspace_role language sql stable security definer set search_path=public as $$select role from workspace_members where workspace_id=w and user_id=auth.uid() and removed_at is null limit 1$$;
do $$declare t text;begin foreach t in array array['workspace_members','projects','people','tasks','checklist_items','task_dependencies','task_people','recurrence_rules','reminders','push_subscriptions','notification_preferences','notification_deliveries','activities','attachments','exports','audit_events','imports','entitlements'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy %I on public.%I for select using (public.is_workspace_member(workspace_id))',t||'_read',t);execute format('create policy %I on public.%I for all using (public.workspace_role_for(workspace_id) in (''owner'',''admin'',''member'')) with check (public.workspace_role_for(workspace_id) in (''owner'',''admin'',''member''))',t||'_write',t);end loop;end$$;
alter table public.workspaces enable row level security;create policy workspaces_read on public.workspaces for select using(public.is_workspace_member(id));create policy workspaces_write on public.workspaces for all using(public.workspace_role_for(id) in('owner','admin'))with check(public.workspace_role_for(id) in('owner','admin'));
alter table public.profiles enable row level security;create policy profiles_self on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());

create or replace function public.bump_version()returns trigger language plpgsql as $$begin new.updated_at=now();new.version=old.version+1;return new;end$$;
do $$declare t text;begin foreach t in array array['profiles','workspaces','projects','people','tasks','checklist_items','task_dependencies','task_people','recurrence_rules','reminders','push_subscriptions','notification_preferences','notification_deliveries','activities','attachments','exports','imports','entitlements'] loop execute format('create trigger %I before update on public.%I for each row execute function public.bump_version()',t||'_bump',t);end loop;end$$;

create or replace function public.enforce_task_completion()returns trigger language plpgsql as $$declare checklist_count int;dependency_count int;begin if new.status='completed' and old.status is distinct from 'completed' then select count(*) into checklist_count from checklist_items where task_id=new.id and required and not completed and deleted_at is null;select count(*) into dependency_count from task_dependencies d join tasks p on p.id=d.prerequisite_task_id where d.waiting_task_id=new.id and d.mandatory and d.deleted_at is null and p.deleted_at is null and not p.archived and p.status not in('completed','cancelled','archived');if checklist_count+dependency_count>0 then raise exception 'Task cannot be completed: % required checklist items and % mandatory prerequisites remain',checklist_count,dependency_count using errcode='P0001';end if;new.completed_at=coalesce(new.completed_at,now());elsif old.status='completed' and new.status<>'completed' then new.completed_at=null;end if;return new;end$$;
create trigger task_completion_guard before update of status on public.tasks for each row execute function public.enforce_task_completion();

create or replace function public.bootstrap_owner_workspace(p_user_id uuid,p_email text)returns jsonb language plpgsql security definer set search_path=public as $$declare w uuid;begin insert into profiles(id,email,display_name)values(p_user_id,p_email,split_part(p_email,'@',1))on conflict(id)do update set email=excluded.email;insert into workspaces(name,created_by)values('My Task Tracker',p_user_id)returning id into w;insert into workspace_members(workspace_id,user_id,role)values(w,p_user_id,'owner');insert into notification_preferences(workspace_id,user_id)values(w,p_user_id);insert into entitlements(workspace_id)values(w);return jsonb_build_object('workspace_id',w,'role','owner');end$$;

create or replace function public.link_dependency_atomic(p_workspace_id uuid,p_user_id uuid,p_waiting_task_id uuid,p_prerequisite_task_id uuid,p_mandatory boolean)returns jsonb language plpgsql security definer set search_path=public as $$declare cycle_found boolean;begin if not exists(select 1 from tasks where id=p_waiting_task_id and workspace_id=p_workspace_id)or not exists(select 1 from tasks where id=p_prerequisite_task_id and workspace_id=p_workspace_id)then raise exception 'Task not found';end if;with recursive downstream(id,path)as(select waiting_task_id,array[prerequisite_task_id,waiting_task_id]from task_dependencies where prerequisite_task_id=p_waiting_task_id and deleted_at is null union all select d.waiting_task_id,x.path||d.waiting_task_id from downstream x join task_dependencies d on d.prerequisite_task_id=x.id where d.deleted_at is null and not d.waiting_task_id=any(x.path))select exists(select 1 from downstream where id=p_prerequisite_task_id)into cycle_found;if cycle_found or p_waiting_task_id=p_prerequisite_task_id then raise exception 'This dependency would create a circular relationship';end if;insert into task_dependencies(workspace_id,waiting_task_id,prerequisite_task_id,mandatory,created_by,updated_by)values(p_workspace_id,p_waiting_task_id,p_prerequisite_task_id,p_mandatory,p_user_id,p_user_id);return jsonb_build_object('linked',true);end$$;
create or replace function public.create_prerequisite_atomic(p_workspace_id uuid,p_user_id uuid,p_waiting_task_id uuid,p_task jsonb,p_mandatory boolean)returns jsonb language plpgsql security definer set search_path=public as $$declare prerequisite tasks;waiting tasks;begin select*into waiting from tasks where id=p_waiting_task_id and workspace_id=p_workspace_id and deleted_at is null;if not found then raise exception 'Waiting task not found';end if;insert into tasks(id,workspace_id,title,description,status,priority,project_id,responsible_person_id,due_date,created_by,updated_by)values(coalesce((p_task->>'id')::uuid,gen_random_uuid()),p_workspace_id,p_task->>'title',coalesce(p_task->>'description',''),coalesce((p_task->>'status')::task_status,'not_started'),coalesce((p_task->>'priority')::task_priority,'medium'),coalesce((p_task->>'projectId')::uuid,waiting.project_id),(p_task->>'responsiblePersonId')::uuid,(p_task->>'dueDate')::date,p_user_id,p_user_id)returning*into prerequisite;perform link_dependency_atomic(p_workspace_id,p_user_id,p_waiting_task_id,prerequisite.id,p_mandatory);return jsonb_build_object('waitingTaskId',waiting.id,'prerequisiteId',prerequisite.id);end$$;

create or replace function public.connected_dashboard(p_workspace_id uuid,p_user_id uuid)returns jsonb language sql security definer set search_path=public as $$with active as(select*from tasks where workspace_id=p_workspace_id and deleted_at is null and not archived and status not in('completed','cancelled','archived')),done as(select*from tasks where workspace_id=p_workspace_id and status='completed' and deleted_at is null),counts as(select count(*)filter(where due_date<current_date)overdue,count(*)filter(where due_date=current_date)today,count(*)filter(where due_date>current_date and due_date<=current_date+7)next7,count(*)filter(where priority='critical')critical,count(*)filter(where priority='high')high,count(*)filter(where blocked)blocked,count(*)filter(where status='waiting')waiting,count(*)active from active),progress as(select coalesce(round(avg(calculated_progress)),0)overall from active)select jsonb_build_object('counts',jsonb_build_object('overdue',coalesce(c.overdue,0),'today',coalesce(c.today,0),'next7',coalesce(c.next7,0),'critical',coalesce(c.critical,0),'high',coalesce(c.high,0),'blocked',coalesce(c.blocked,0),'waiting',coalesce(c.waiting,0),'active',coalesce(c.active,0)),'overallProgress',p.overall,'projectProgress','[]'::jsonb,'peopleProgress','[]'::jsonb,'workload','[]'::jsonb)from counts c full join progress p on true$$;
create or replace function public.connected_people_workload(p_workspace_id uuid,p_user_id uuid,p_role text default null)returns jsonb language sql security definer set search_path=public as $$select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'fullName',p.full_name,'role',p.role,'company',p.company,'activeTasks',coalesce(s.active,0),'progress',coalesce(s.progress,0))order by p.full_name),'[]'::jsonb)from people p left join lateral(select count(*)filter(where t.status not in('completed','cancelled','archived')and t.deleted_at is null)active,round(avg(t.calculated_progress))progress from tasks t where t.responsible_person_id=p.id)s on true where p.workspace_id=p_workspace_id and p.deleted_at is null and(p_role is null or p.role ilike'%'||p_role||'%')$$;
create or replace function public.connected_projects_workload(p_workspace_id uuid,p_user_id uuid)returns jsonb language sql security definer set search_path=public as $$select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'color',p.color,'description',p.description,'activeTasks',coalesce(s.active,0),'progress',coalesce(s.progress,0))order by p.name),'[]'::jsonb)from projects p left join lateral(select count(*)filter(where t.status not in('completed','cancelled','archived')and t.deleted_at is null)active,round(avg(t.calculated_progress))progress from tasks t where t.project_id=p.id and t.deleted_at is null)s on true where p.workspace_id=p_workspace_id and p.deleted_at is null and not p.archived$$;
create or replace function public.connected_calendar(p_workspace_id uuid,p_user_id uuid,p_start date,p_end date)returns jsonb language sql security definer set search_path=public as $$with dates as(select generate_series(p_start,p_end,'1 day')::date d),matches as(select d.d,t.*,p.name project_name,pe.full_name person_name,case when t.status='completed' then'green'when(t.due_date<current_date and t.status not in('completed','cancelled','archived'))or t.priority='critical'then'red'when t.priority='high'then'orange'else'blue'end severity from dates d join tasks t on t.workspace_id=p_workspace_id and t.deleted_at is null and(t.due_date=d.d or t.reminder_at::date=d.d or t.completed_at::date=d.d)left join projects p on p.id=t.project_id left join people pe on pe.id=t.responsible_person_id),per_day as(select d,jsonb_agg(jsonb_build_object('id',id,'title',title,'description',description,'status',status,'priority',priority,'dueDate',due_date,'dueTime',due_time,'projectId',project_id,'projectName',project_name,'responsiblePersonId',responsible_person_id,'responsiblePersonName',person_name,'calculatedProgress',calculated_progress,'blocked',blocked,'version',version,'updatedAt',updated_at))tasks,count(*)count,case when bool_or(severity='red')then'red'when bool_or(severity='orange')then'orange'when bool_or(severity='blue')then'blue'else'green'end severity from matches group by d)select coalesce(jsonb_agg(jsonb_build_object('date',dates.d,'severity',coalesce(per_day.severity,'neutral'),'count',coalesce(per_day.count,0),'tasks',coalesce(per_day.tasks,'[]'::jsonb))order by dates.d),'[]'::jsonb)from dates left join per_day using(d)$$;
create or replace function public.connected_dependency_load(p_workspace_id uuid,p_user_id uuid)returns jsonb language sql security definer set search_path=public as $$with recursive paths as(select d.prerequisite_task_id,d.waiting_task_id,1 depth,array[d.prerequisite_task_id,d.waiting_task_id]path from task_dependencies d join tasks p on p.id=d.prerequisite_task_id join tasks w on w.id=d.waiting_task_id where d.workspace_id=p_workspace_id and d.mandatory and d.deleted_at is null and p.deleted_at is null and p.status not in('completed','cancelled','archived')and w.deleted_at is null and not w.archived and w.status not in('completed','cancelled','archived')union all select x.prerequisite_task_id,d.waiting_task_id,x.depth+1,x.path||d.waiting_task_id from paths x join task_dependencies d on d.prerequisite_task_id=x.waiting_task_id join tasks w on w.id=d.waiting_task_id where d.deleted_at is null and w.deleted_at is null and not w.archived and w.status not in('completed','cancelled','archived')and not d.waiting_task_id=any(x.path)and x.depth<50),distinct_paths as(select distinct prerequisite_task_id,waiting_task_id,depth from paths),scored as(select p.responsible_person_id,count(distinct p.id)blocking_prerequisites,count(distinct x.waiting_task_id)affected_tasks,count(distinct w.project_id)filter(where w.project_id is not null)affected_projects,count(distinct p.id)filter(where p.due_date<current_date)overdue_prerequisites,count(distinct w.id)filter(where w.priority in('critical','high'))critical_high,max(x.depth)max_depth from distinct_paths x join tasks p on p.id=x.prerequisite_task_id join tasks w on w.id=x.waiting_task_id group by p.responsible_person_id)select coalesce(jsonb_agg(jsonb_build_object('personId',s.responsible_person_id,'personName',coalesce(pe.full_name,'Unassigned'),'blockingPrerequisites',s.blocking_prerequisites,'affectedTasks',s.affected_tasks,'affectedProjects',s.affected_projects,'overduePrerequisites',s.overdue_prerequisites,'criticalHighImpact',s.critical_high,'impactScore',s.affected_tasks*10+s.affected_projects*20+s.overdue_prerequisites*25+s.critical_high*30+greatest(s.max_depth-1,0)*5)order by(s.affected_tasks*10+s.affected_projects*20+s.overdue_prerequisites*25+s.critical_high*30+greatest(s.max_depth-1,0)*5)desc,s.affected_tasks desc,s.affected_projects desc,coalesce(pe.full_name,'Unassigned')),'[]'::jsonb)from scored s left join people pe on pe.id=s.responsible_person_id$$;

create or replace function public.process_due_reminders(p_workspace_id uuid,p_user_id uuid,p_limit int default 50)returns jsonb language plpgsql security definer set search_path=public as $$declare result jsonb;begin with due as(select r.id from reminders r join tasks t on t.id=r.task_id where r.workspace_id=p_workspace_id and r.dismissed=false and r.deleted_at is null and r.next_attempt_at<=now()and t.deleted_at is null and t.status not in('completed','cancelled','archived')and(r.claimed_at is null or r.claimed_at<now()-interval'10 minutes')order by r.next_attempt_at for update skip locked limit least(p_limit,50)),claimed as(update reminders r set claimed_at=now(),attempt_count=attempt_count+1 from due where r.id=due.id returning r.*),deliveries as(insert into notification_deliveries(workspace_id,user_id,task_id,reminder_id,kind,idempotency_key)select workspace_id,user_id,task_id,id,'reminder',id::text||':'||scheduled_at::text from claimed on conflict(workspace_id,idempotency_key)do nothing returning*)select coalesce(jsonb_agg(jsonb_build_object('id',d.id,'taskId',d.task_id,'userId',d.user_id,'title',t.title,'kind','Reminder','dateLabel',r.scheduled_at::text,'emailEnabled',coalesce(np.email_enabled,false))),'[]'::jsonb)into result from deliveries d join tasks t on t.id=d.task_id join reminders r on r.id=d.reminder_id left join notification_preferences np on np.workspace_id=d.workspace_id and np.user_id=d.user_id;return result;end$$;

create or replace function public.preview_local_import(p_workspace_id uuid,p_user_id uuid,p_import_id uuid,p_snapshot jsonb,p_dry_run boolean default true)returns jsonb language plpgsql security definer set search_path=public as $$begin if p_snapshot is null or jsonb_typeof(p_snapshot)<>'object'then raise exception'Invalid backup payload';end if;if exists(select 1 from imports where id=p_import_id and workspace_id=p_workspace_id and status='applied')then raise exception'This backup was already imported';end if;return jsonb_build_object('valid',true,'dryRun',true,'counts',jsonb_build_object('tasks',jsonb_array_length(coalesce(p_snapshot->'tasks','[]')),'projects',jsonb_array_length(coalesce(p_snapshot->'projects','[]')),'people',jsonb_array_length(coalesce(p_snapshot->'people','[]'))),'warnings','["Attachments require separate upload"]'::jsonb);end$$;
create or replace function public.apply_local_import(p_workspace_id uuid,p_user_id uuid,p_import_id uuid,p_snapshot jsonb,p_dry_run boolean default false)returns jsonb language plpgsql security definer set search_path=public as $$declare preview jsonb;begin preview:=preview_local_import(p_workspace_id,p_user_id,p_import_id,p_snapshot,true);if p_dry_run then return preview;end if;insert into imports(id,workspace_id,status,counts,safety_snapshot,created_by)values(p_import_id,p_workspace_id,'applying',preview->'counts',jsonb_build_object('tasks',(select count(*)from tasks where workspace_id=p_workspace_id)),p_user_id);insert into projects(id,workspace_id,name,color,description,created_by,updated_by)select coalesce((x->>'id')::uuid,gen_random_uuid()),p_workspace_id,x->>'name',coalesce(x->>'color','#2563eb'),coalesce(x->>'description',''),p_user_id,p_user_id from jsonb_array_elements(coalesce(p_snapshot->'projects','[]'))x on conflict do nothing;insert into people(id,workspace_id,full_name,company,role,email,created_by,updated_by)select coalesce((x->>'id')::uuid,gen_random_uuid()),p_workspace_id,coalesce(x->>'fullName',x->>'full_name'),coalesce(x->>'company',''),coalesce(x->>'role',''),coalesce(x->>'email',''),p_user_id,p_user_id from jsonb_array_elements(coalesce(p_snapshot->'people','[]'))x on conflict do nothing;insert into tasks(id,workspace_id,title,description,status,priority,due_date,project_id,responsible_person_id,created_by,updated_by)select coalesce((x->>'id')::uuid,gen_random_uuid()),p_workspace_id,x->>'title',coalesce(x->>'description',''),coalesce((x->>'status')::task_status,'not_started'),coalesce((x->>'priority')::task_priority,'medium'),coalesce(x->>'dueDate',x->>'due_date')::date,coalesce(x->>'projectId',x->>'project_id')::uuid,coalesce(x->>'responsiblePersonId',x->>'responsible_person_id')::uuid,p_user_id,p_user_id from jsonb_array_elements(coalesce(p_snapshot->'tasks','[]'))x on conflict do nothing;update imports set status='applied'where id=p_import_id;return preview||jsonb_build_object('applied',true);exception when others then update imports set status='failed'where id=p_import_id;raise;end$$;

revoke all on all tables in schema public from anon,authenticated;grant select on public.profiles,public.workspaces,public.workspace_members,public.projects,public.people,public.tasks,public.checklist_items,public.task_dependencies,public.task_people,public.reminders,public.notification_preferences,public.activities to authenticated;
revoke execute on function public.bootstrap_owner_workspace(uuid,text),public.link_dependency_atomic(uuid,uuid,uuid,uuid,boolean),public.create_prerequisite_atomic(uuid,uuid,uuid,jsonb,boolean),public.connected_dashboard(uuid,uuid),public.connected_projects_workload(uuid,uuid),public.connected_people_workload(uuid,uuid,text),public.connected_calendar(uuid,uuid,date,date),public.connected_dependency_load(uuid,uuid),public.process_due_reminders(uuid,uuid,int),public.preview_local_import(uuid,uuid,uuid,jsonb,boolean),public.apply_local_import(uuid,uuid,uuid,jsonb,boolean)from public,anon,authenticated;
grant execute on all functions in schema public to service_role;
insert into public.schema_versions(version)values(1);
commit;
