begin;

do $$ begin create type public.invite_status as enum ('pending','accepted','expired','revoked','disabled'); exception when duplicate_object then null; end $$;
alter table public.profiles add column if not exists account_status text not null default 'active' check(account_status in('active','disabled','deleting','deleted')),add column if not exists must_change_password boolean not null default false,add column if not exists disabled_at timestamptz,add column if not exists last_sign_in_at timestamptz;
alter table public.workspaces add column if not exists personal_owner_user_id uuid references auth.users(id) on delete set null;
update public.workspaces set personal_owner_user_id=created_by where product_edition='connected' and created_by is not null and personal_owner_user_id is null and not exists(select 1 from public.workspaces x where x.personal_owner_user_id=workspaces.created_by);
create unique index if not exists one_personal_workspace_per_user on public.workspaces(personal_owner_user_id) where personal_owner_user_id is not null;

create table if not exists public.platform_admins(user_id uuid primary key references auth.users(id) on delete cascade,email_normalized text not null unique,created_at timestamptz not null default now(),disabled_at timestamptz);
create table if not exists public.app_invites(id uuid primary key default gen_random_uuid(),email_normalized text not null,status public.invite_status not null default 'pending',invited_by uuid not null references auth.users(id),invited_at timestamptz not null default now(),expires_at timestamptz not null default now()+interval '7 days',accepted_at timestamptz,accepted_user_id uuid references auth.users(id) on delete set null,disabled_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version int not null default 1);
create unique index if not exists one_active_invite_per_email on public.app_invites(email_normalized) where status in('pending','accepted');
create index if not exists app_invites_recent on public.app_invites(invited_at desc);
create table if not exists public.scheduler_runs(id uuid primary key default gen_random_uuid(),started_at timestamptz not null default now(),completed_at timestamptz,claimed_count int not null default 0,delivered_count int not null default 0,failed_count int not null default 0,status text not null default 'running',request_id text);
create table if not exists public.account_deletion_snapshots(id uuid primary key default gen_random_uuid(),user_reference_hash text not null,encrypted_by_provider boolean not null default true,payload jsonb not null,created_at timestamptz not null default now(),expires_at timestamptz not null default now()+interval '30 days');
alter table public.notification_deliveries add column if not exists next_attempt_at timestamptz not null default now(),add column if not exists claimed_at timestamptz,add column if not exists email_sent boolean not null default false,add column if not exists push_sent boolean not null default false;
alter table public.exports add column if not exists payload jsonb;
alter table public.audit_events alter column workspace_id drop not null;
create index if not exists delivery_claim_queue on public.notification_deliveries(status,next_attempt_at) where status in('pending','retry');
create index if not exists members_active_user on public.workspace_members(user_id,workspace_id) where removed_at is null;
create index if not exists profiles_account_status on public.profiles(account_status);

alter table public.platform_admins enable row level security;alter table public.app_invites enable row level security;alter table public.scheduler_runs enable row level security;alter table public.account_deletion_snapshots enable row level security;
drop policy if exists workspace_members_write on public.workspace_members;create policy workspace_members_write on public.workspace_members for all using(public.workspace_role_for(workspace_id) in('owner','admin')) with check(public.workspace_role_for(workspace_id) in('owner','admin'));
drop policy if exists push_subscriptions_read on public.push_subscriptions;drop policy if exists push_subscriptions_write on public.push_subscriptions;create policy push_subscriptions_self on public.push_subscriptions for all using(user_id=auth.uid() and public.is_workspace_member(workspace_id)) with check(user_id=auth.uid() and public.is_workspace_member(workspace_id));
drop policy if exists notification_preferences_read on public.notification_preferences;drop policy if exists notification_preferences_write on public.notification_preferences;create policy notification_preferences_self on public.notification_preferences for all using(user_id=auth.uid() and public.is_workspace_member(workspace_id)) with check(user_id=auth.uid() and public.is_workspace_member(workspace_id));
drop policy if exists notification_deliveries_read on public.notification_deliveries;drop policy if exists notification_deliveries_write on public.notification_deliveries;create policy notification_deliveries_self_read on public.notification_deliveries for select using(user_id=auth.uid() and public.is_workspace_member(workspace_id));
drop policy if exists reminders_read on public.reminders;drop policy if exists reminders_write on public.reminders;create policy reminders_self on public.reminders for all using(user_id=auth.uid() and public.is_workspace_member(workspace_id)) with check(user_id=auth.uid() and public.is_workspace_member(workspace_id));

create or replace function public.normalize_email(value text)returns text language sql immutable strict as $$select lower(trim(value))$$;
create or replace function public.is_platform_admin(candidate uuid)returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from platform_admins where user_id=candidate and disabled_at is null)$$;
create or replace function public.provision_private_workspace(p_user_id uuid,p_email text)returns jsonb language plpgsql security definer set search_path=public as $$declare w uuid;normalized text:=normalize_email(p_email);begin
insert into profiles(id,email,display_name,account_status)values(p_user_id,normalized,split_part(normalized,'@',1),'active')on conflict(id)do update set email=excluded.email,account_status=case when profiles.account_status='deleted'then profiles.account_status else'active'end,last_sign_in_at=now();
insert into workspaces(name,created_by,personal_owner_user_id)values('My Task Tracker',p_user_id,p_user_id)on conflict(personal_owner_user_id)where personal_owner_user_id is not null do update set personal_owner_user_id=excluded.personal_owner_user_id returning id into w;
insert into workspace_members(workspace_id,user_id,role,removed_at)values(w,p_user_id,'owner',null)on conflict(workspace_id,user_id)do update set role='owner',removed_at=null;
insert into notification_preferences(workspace_id,user_id,email_enabled,push_enabled)values(w,p_user_id,false,true)on conflict(workspace_id,user_id)do nothing;
insert into entitlements(workspace_id,product_edition,plan,max_users)values(w,'connected','owner_free',1)on conflict(workspace_id,product_edition)do nothing;
return jsonb_build_object('workspaceId',w,'role','owner');end$$;
create or replace function public.bootstrap_platform_owner(p_user_id uuid,p_email text)returns jsonb language plpgsql security definer set search_path=public as $$declare provisioned jsonb;normalized text:=normalize_email(p_email);begin if exists(select 1 from platform_admins where disabled_at is null)and not exists(select 1 from platform_admins where user_id=p_user_id and disabled_at is null)then raise exception'Platform owner has already been bootstrapped'using errcode='42501';end if;insert into platform_admins(user_id,email_normalized)values(p_user_id,normalized)on conflict(user_id)do update set email_normalized=excluded.email_normalized,disabled_at=null;provisioned:=provision_private_workspace(p_user_id,normalized);return provisioned||jsonb_build_object('platformAdmin',true);end$$;
create or replace function public.connected_identity_state(p_user_id uuid,p_email text)returns jsonb language plpgsql security definer set search_path=public as $$declare m record;s text;i app_invites;n text:=normalize_email(p_email);begin select account_status into s from profiles where id=p_user_id;select wm.workspace_id,wm.role into m from workspace_members wm join workspaces w on w.id=wm.workspace_id where wm.user_id=p_user_id and wm.removed_at is null and w.product_edition='connected'order by wm.created_at limit 1;select*into i from app_invites where email_normalized=n and status='pending'order by invited_at desc limit 1;if i.id is not null and i.expires_at<=now()then update app_invites set status='expired'where id=i.id;i:=null;end if;return jsonb_build_object('status',case when s='disabled'then'disabled'when m.workspace_id is not null then'active'when i.id is not null then'invited'else'uninvited'end,'userId',p_user_id,'email',n,'workspaceId',m.workspace_id,'role',m.role,'platformAdmin',is_platform_admin(p_user_id),'requiresPasswordSetup',coalesce((select must_change_password from profiles where id=p_user_id),i.id is not null));end$$;
create or replace function public.create_app_invitation(p_actor_user_id uuid,p_email text,p_user_limit int default 20,p_expiry_days int default 7)returns jsonb language plpgsql security definer set search_path=public as $$declare n text:=normalize_email(p_email);r app_invites;c int;begin if not is_platform_admin(p_actor_user_id)then raise exception'Platform administrator required'using errcode='42501';end if;update app_invites set status='expired',updated_at=now()where status='pending'and expires_at<=now();if length(n)>320 or n!~'^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'then raise exception'Invalid email address';end if;if(select count(*)from app_invites where invited_by=p_actor_user_id and invited_at>now()-interval'1 hour')>=10 then raise exception'Invitation rate limit reached';end if;select(select count(*)from app_invites where status in('pending','accepted'))+(select count(*)from platform_admins where disabled_at is null)into c;if c>=least(greatest(p_user_limit,1),100)then raise exception'Connected user limit reached';end if;if exists(select 1 from app_invites where email_normalized=n and status in('pending','accepted'))then raise exception'An active invitation already exists';end if;insert into app_invites(email_normalized,invited_by,expires_at)values(n,p_actor_user_id,now()+make_interval(days=>least(greatest(p_expiry_days,1),30)))returning*into r;return jsonb_build_object('id',r.id,'email',r.email_normalized,'status',r.status,'invitedAt',r.invited_at,'expiresAt',r.expires_at);end$$;
create or replace function public.accept_app_invitation(p_user_id uuid,p_email text)returns jsonb language plpgsql security definer set search_path=public as $$declare i app_invites;p jsonb;n text:=normalize_email(p_email);begin select*into i from app_invites where email_normalized=n and status='pending'order by invited_at desc limit 1 for update;if i.id is null then if exists(select 1 from workspaces where personal_owner_user_id=p_user_id)then return provision_private_workspace(p_user_id,n);end if;raise exception'No valid invitation is available'using errcode='42501';end if;if i.expires_at<=now()then update app_invites set status='expired'where id=i.id;raise exception'Invitation has expired';end if;if i.accepted_user_id is not null and i.accepted_user_id<>p_user_id then raise exception'Invitation belongs to another account'using errcode='42501';end if;p:=provision_private_workspace(p_user_id,n);update app_invites set status='accepted',accepted_at=coalesce(accepted_at,now()),accepted_user_id=p_user_id where id=i.id;return p||jsonb_build_object('invitationId',i.id,'accepted',true);end$$;
create or replace function public.list_app_users(p_actor_user_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare r jsonb;begin if not is_platform_admin(p_actor_user_id)then raise exception'Platform administrator required'using errcode='42501';end if;select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'email',i.email_normalized,'status',i.status,'invitedAt',i.invited_at,'expiresAt',i.expires_at,'acceptedAt',i.accepted_at,'acceptedUserId',i.accepted_user_id,'disabledAt',i.disabled_at)order by i.invited_at desc),'[]')into r from app_invites i;return r;end$$;
create or replace function public.change_app_invitation(p_actor_user_id uuid,p_invitation_id uuid,p_action text)returns jsonb language plpgsql security definer set search_path=public as $$declare r app_invites;begin if not is_platform_admin(p_actor_user_id)then raise exception'Platform administrator required'using errcode='42501';end if;if p_action='revoke'then update app_invites set status='revoked',updated_at=now()where id=p_invitation_id and status='pending'returning*into r;elsif p_action='resent'then update app_invites set invited_at=now(),expires_at=now()+interval'7 days',updated_at=now()where id=p_invitation_id and status='pending'returning*into r;else raise exception'Unsupported invitation action';end if;if r.id is null then raise exception'Invitation cannot be changed';end if;return jsonb_build_object('id',r.id,'email',r.email_normalized,'status',r.status,'invitedAt',r.invited_at,'expiresAt',r.expires_at);end$$;
create or replace function public.set_connected_user_access(p_actor_user_id uuid,p_target_user_id uuid,p_enabled boolean)returns jsonb language plpgsql security definer set search_path=public as $$declare n int;begin if not is_platform_admin(p_actor_user_id)then raise exception'Platform administrator required'using errcode='42501';end if;if p_actor_user_id=p_target_user_id and not p_enabled then raise exception'The active platform owner cannot disable themselves';end if;update profiles set account_status=case when p_enabled then'active'else'disabled'end,disabled_at=case when p_enabled then null else now()end where id=p_target_user_id;get diagnostics n=row_count;if n=0 then raise exception'User not found';end if;update workspace_members set removed_at=case when p_enabled then null else now()end where user_id=p_target_user_id;update push_subscriptions set disabled=not p_enabled where user_id=p_target_user_id;update app_invites set status=case when p_enabled then'accepted'::invite_status else'disabled'::invite_status end,disabled_at=case when p_enabled then null else now()end where accepted_user_id=p_target_user_id;return jsonb_build_object('userId',p_target_user_id,'enabled',p_enabled);end$$;
create or replace function public.connected_usage_summary(p_actor_user_id uuid,p_user_limit int default 20)returns jsonb language plpgsql security definer set search_path=public as $$declare r jsonb;begin if not is_platform_admin(p_actor_user_id)then raise exception'Platform administrator required'using errcode='42501';end if;select jsonb_build_object('acceptedUsers',(select count(*)from app_invites where status='accepted')+(select count(*)from platform_admins where disabled_at is null),'pendingInvitations',(select count(*)from app_invites where status='pending'and expires_at>now()),'userLimit',p_user_limit,'records',jsonb_build_object('tasks',(select count(*)from tasks),'projects',(select count(*)from projects),'people',(select count(*)from people),'reminders',(select count(*)from reminders)),'approximateStorageBytes',(select coalesce(sum(pg_column_size(x)),0)from tasks x),'emailsSentToday',(select count(*)from notification_deliveries where email_sent and delivered_at>=current_date),'emailsSentThisMonth',(select count(*)from notification_deliveries where email_sent and delivered_at>=date_trunc('month',now())),'failedNotifications',(select count(*)from notification_deliveries where status='failed'),'pendingDeliveries',(select count(*)from notification_deliveries where status in('pending','retry')),'oldestPendingDelivery',(select min(created_at)from notification_deliveries where status in('pending','retry')),'lastCronAt',(select max(completed_at)from scheduler_runs where status='completed'),'lastExportAt',(select max(created_at)from exports where status='ready'))into r;return r;end$$;
create or replace function public.claim_due_notification_deliveries(p_limit int default 25,p_request_id text default null)returns jsonb language plpgsql security definer set search_path=public as $$declare r jsonb;run uuid;b int:=least(greatest(p_limit,1),50);begin insert into scheduler_runs(request_id)values(p_request_id)returning id into run;insert into notification_deliveries(workspace_id,user_id,task_id,reminder_id,kind,idempotency_key,next_attempt_at)select x.workspace_id,x.user_id,x.task_id,x.id,'reminder',x.id::text||':'||x.scheduled_at::text,now()from reminders x join tasks t on t.id=x.task_id and t.workspace_id=x.workspace_id join profiles p on p.id=x.user_id and p.account_status='active'join workspace_members wm on wm.workspace_id=x.workspace_id and wm.user_id=x.user_id and wm.removed_at is null where x.dismissed=false and x.deleted_at is null and x.next_attempt_at<=now()and t.deleted_at is null and not t.archived and t.status not in('completed','cancelled','archived')on conflict(workspace_id,idempotency_key)do nothing;with due as(select id from notification_deliveries where status in('pending','retry')and next_attempt_at<=now()and(claimed_at is null or claimed_at<now()-interval'10 minutes')order by next_attempt_at for update skip locked limit b),claimed as(update notification_deliveries d set claimed_at=now(),attempt_count=attempt_count+1 from due where d.id=due.id returning d.*)select coalesce(jsonb_agg(jsonb_build_object('deliveryId',d.id,'workspaceId',d.workspace_id,'userId',d.user_id,'recipientEmail',p.email,'taskId',d.task_id,'title',t.title,'reminderTime',x.scheduled_at,'emailEnabled',coalesce(np.email_enabled,false),'pushEnabled',coalesce(np.push_enabled,true),'emailSent',d.email_sent,'pushSent',d.push_sent,'idempotencyKey',d.idempotency_key,'attemptCount',d.attempt_count)),'[]')into r from claimed d join profiles p on p.id=d.user_id join tasks t on t.id=d.task_id join reminders x on x.id=d.reminder_id left join notification_preferences np on np.workspace_id=d.workspace_id and np.user_id=d.user_id;update scheduler_runs set claimed_count=jsonb_array_length(r),completed_at=now(),status='completed'where id=run;return r;end$$;
create or replace function public.complete_notification_delivery(p_delivery_id uuid,p_status text,p_error_code text default null,p_next_attempt_at timestamptz default null,p_email_sent boolean default false,p_push_sent boolean default false)returns jsonb language plpgsql security definer set search_path=public as $$declare d notification_deliveries;begin if p_status not in('delivered','retry','failed','quota_reached')then raise exception'Invalid delivery status';end if;update notification_deliveries set status=p_status,last_error_code=left(p_error_code,100),next_attempt_at=coalesce(p_next_attempt_at,next_attempt_at),email_sent=email_sent or p_email_sent,push_sent=push_sent or p_push_sent,delivered_at=case when p_status='delivered'then now()else delivered_at end,claimed_at=null where id=p_delivery_id returning*into d;if d.id is null then raise exception'Delivery not found';end if;if p_status='delivered'then update reminders set dismissed=true where id=d.reminder_id;end if;return jsonb_build_object('deliveryId',d.id,'status',d.status);end$$;
create or replace function public.notification_email_count_today()returns int language sql security definer set search_path=public as $$select count(*)::int from notification_deliveries where email_sent and delivered_at>=current_date$$;
create or replace function public.prepare_connected_account_deletion(p_actor_user_id uuid,p_target_user_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare w uuid;s uuid;p jsonb;begin if p_actor_user_id<>p_target_user_id and not is_platform_admin(p_actor_user_id)then raise exception'Account deletion is not authorized'using errcode='42501';end if;if is_platform_admin(p_target_user_id)then raise exception'Transfer or remove platform administration before deletion';end if;select id into w from workspaces where personal_owner_user_id=p_target_user_id limit 1 for update;if w is null then raise exception'Personal workspace not found';end if;update profiles set account_status='deleting'where id=p_target_user_id;select jsonb_build_object('format','task-tracker-account-safety','version',2,'workspaceId',w,'tasks',(select coalesce(jsonb_agg(to_jsonb(x)),'[]')from tasks x where workspace_id=w),'projects',(select coalesce(jsonb_agg(to_jsonb(x)),'[]')from projects x where workspace_id=w),'people',(select coalesce(jsonb_agg(to_jsonb(x)),'[]')from people x where workspace_id=w))into p;insert into account_deletion_snapshots(user_reference_hash,payload)values(encode(digest(p_target_user_id::text,'sha256'),'hex'),p)returning id into s;delete from workspaces where id=w;update app_invites set status='disabled',disabled_at=now()where accepted_user_id=p_target_user_id;return jsonb_build_object('prepared',true,'snapshotId',s,'authUserId',p_target_user_id);end$$;

create or replace function public.assert_connected_workspace(p_workspace_id uuid)returns void language plpgsql security definer set search_path=public as $$begin if auth.uid()is null or not exists(select 1 from workspace_members where workspace_id=p_workspace_id and user_id=auth.uid()and removed_at is null)or exists(select 1 from profiles where id=auth.uid()and account_status<>'active')then raise exception'Workspace access denied'using errcode='42501';end if;end$$;
create or replace function public.user_connected_dashboard(p_workspace_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return connected_dashboard(p_workspace_id,auth.uid());end$$;
create or replace function public.user_connected_projects_workload(p_workspace_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return connected_projects_workload(p_workspace_id,auth.uid());end$$;
create or replace function public.user_connected_people_workload(p_workspace_id uuid,p_role text default null)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return connected_people_workload(p_workspace_id,auth.uid(),p_role);end$$;
create or replace function public.user_connected_calendar(p_workspace_id uuid,p_start date,p_end date)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return connected_calendar(p_workspace_id,auth.uid(),p_start,p_end);end$$;
create or replace function public.user_connected_dependency_load(p_workspace_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return connected_dependency_load(p_workspace_id,auth.uid());end$$;
create or replace function public.user_link_dependency_atomic(p_workspace_id uuid,p_waiting_task_id uuid,p_prerequisite_task_id uuid,p_mandatory boolean)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return link_dependency_atomic(p_workspace_id,auth.uid(),p_waiting_task_id,p_prerequisite_task_id,p_mandatory);end$$;
create or replace function public.user_create_prerequisite_atomic(p_workspace_id uuid,p_waiting_task_id uuid,p_task jsonb,p_mandatory boolean)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return create_prerequisite_atomic(p_workspace_id,auth.uid(),p_waiting_task_id,p_task,p_mandatory);end$$;
create or replace function public.user_preview_local_import(p_workspace_id uuid,p_import_id uuid,p_snapshot jsonb,p_dry_run boolean default true)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return preview_local_import(p_workspace_id,auth.uid(),p_import_id,p_snapshot,p_dry_run);end$$;
create or replace function public.user_apply_local_import(p_workspace_id uuid,p_import_id uuid,p_snapshot jsonb,p_dry_run boolean default false)returns jsonb language plpgsql security definer set search_path=public as $$begin perform assert_connected_workspace(p_workspace_id);return apply_local_import(p_workspace_id,auth.uid(),p_import_id,p_snapshot,p_dry_run);end$$;

create or replace function public.enforce_same_workspace_reference()returns trigger language plpgsql set search_path=public as $$begin if tg_table_name='tasks'then if new.project_id is not null and not exists(select 1 from projects where id=new.project_id and workspace_id=new.workspace_id)then raise exception'Project belongs to another workspace';end if;if new.responsible_person_id is not null and not exists(select 1 from people where id=new.responsible_person_id and workspace_id=new.workspace_id)then raise exception'Person belongs to another workspace';end if;elsif tg_table_name='checklist_items'then if not exists(select 1 from tasks where id=new.task_id and workspace_id=new.workspace_id)then raise exception'Task belongs to another workspace';end if;elsif tg_table_name='task_dependencies'then if not exists(select 1 from tasks where id=new.waiting_task_id and workspace_id=new.workspace_id)or not exists(select 1 from tasks where id=new.prerequisite_task_id and workspace_id=new.workspace_id)then raise exception'Dependency crosses workspaces';end if;elsif tg_table_name='task_people'then if not exists(select 1 from tasks where id=new.task_id and workspace_id=new.workspace_id)or not exists(select 1 from people where id=new.person_id and workspace_id=new.workspace_id)then raise exception'Task contact crosses workspaces';end if;elsif tg_table_name in('reminders','recurrence_rules')then if not exists(select 1 from tasks where id=new.task_id and workspace_id=new.workspace_id)then raise exception'Task belongs to another workspace';end if;end if;return new;end$$;
do $$declare t text;begin foreach t in array array['tasks','checklist_items','task_dependencies','task_people','reminders','recurrence_rules']loop execute format('drop trigger if exists %I on public.%I',t||'_workspace_guard',t);execute format('create trigger %I before insert or update on public.%I for each row execute function public.enforce_same_workspace_reference()',t||'_workspace_guard',t);end loop;end$$;

grant select,insert,update,delete on public.projects,public.people,public.tasks,public.checklist_items,public.task_dependencies,public.task_people,public.reminders,public.recurrence_rules,public.push_subscriptions,public.notification_preferences,public.activities,public.attachments,public.exports,public.imports to authenticated;
grant select on public.notification_deliveries,public.audit_events to authenticated;grant select,update on public.profiles,public.workspaces,public.workspace_members,public.entitlements to authenticated;
revoke all on public.platform_admins,public.app_invites,public.scheduler_runs,public.account_deletion_snapshots from anon,authenticated;
revoke execute on all functions in schema public from public,anon,authenticated;
grant execute on function public.is_workspace_member(uuid),public.workspace_role_for(uuid),public.assert_connected_workspace(uuid),public.user_connected_dashboard(uuid),public.user_connected_projects_workload(uuid),public.user_connected_people_workload(uuid,text),public.user_connected_calendar(uuid,date,date),public.user_connected_dependency_load(uuid),public.user_link_dependency_atomic(uuid,uuid,uuid,boolean),public.user_create_prerequisite_atomic(uuid,uuid,jsonb,boolean),public.user_preview_local_import(uuid,uuid,jsonb,boolean),public.user_apply_local_import(uuid,uuid,jsonb,boolean)to authenticated;
grant execute on all functions in schema public to service_role;
insert into public.schema_versions(version)values(2)on conflict(version)do nothing;
commit;
